export interface DetectionRule {
  service: string
  senderDomains: string[]
  subjectPatterns: RegExp[]
  bodyKeywords: string[]
  trialIndicators: string[]
  priceExtractor: RegExp
  dateExtractor: RegExp
  currencyExtractor?: RegExp
}

export const DETECTION_RULES: DetectionRule[] = [
  {
    service: 'Netflix',
    senderDomains: ['netflix.com', 'email.netflix.com'],
    subjectPatterns: [/netflix.*membership/i, /welcome to netflix/i, /your netflix/i],
    bodyKeywords: ['monthly charge', 'subscription', 'membership'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Spotify',
    senderDomains: ['spotify.com', 'email.spotify.com'],
    subjectPatterns: [/spotify.*premium/i, /welcome to spotify/i],
    bodyKeywords: ['premium', 'subscription', 'billing'],
    trialIndicators: ['free trial', 'trial period', 'free for'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Disney+',
    senderDomains: ['disneyplus.com', 'email.disneyplus.com'],
    subjectPatterns: [/disney.*subscription/i, /welcome to disney/i],
    bodyKeywords: ['subscription', 'billing', 'membership'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Amazon Prime',
    senderDomains: ['amazon.com', 'email.amazon.com'],
    subjectPatterns: [/prime.*membership/i, /amazon prime/i],
    bodyKeywords: ['prime', 'membership', 'subscription'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly|\/year|per year)/i,
    dateExtractor: /(?:on|starting)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'YouTube Premium',
    senderDomains: ['youtube.com', 'email.youtube.com', 'google.com'],
    subjectPatterns: [/youtube.*premium/i, /youtube.*subscription/i],
    bodyKeywords: ['premium', 'subscription', 'membership'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  // AI Services
  {
    service: 'ChatGPT Plus',
    senderDomains: ['openai.com', 'email.openai.com'],
    subjectPatterns: [/chatgpt.*plus/i, /openai.*subscription/i, /your.*openai/i, /chatgpt.*receipt/i],
    bodyKeywords: ['chatgpt plus', 'subscription', 'gpt-4', 'billing', 'openai'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Claude Pro',
    senderDomains: ['anthropic.com', 'mail.anthropic.com'],
    subjectPatterns: [/claude.*pro/i, /anthropic.*subscription/i, /your.*claude/i],
    bodyKeywords: ['claude pro', 'subscription', 'anthropic', 'billing'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Midjourney',
    senderDomains: ['midjourney.com', 'mail.midjourney.com'],
    subjectPatterns: [/midjourney.*subscription/i, /midjourney.*plan/i, /welcome.*midjourney/i],
    bodyKeywords: ['midjourney', 'subscription', 'basic plan', 'standard plan', 'pro plan'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'GitHub Copilot',
    senderDomains: ['github.com', 'email.github.com'],
    subjectPatterns: [/copilot.*subscription/i, /github.*copilot/i, /copilot.*billing/i],
    bodyKeywords: ['copilot', 'subscription', 'github', 'billing', 'ai assistant'],
    trialIndicators: ['free trial', 'trial period', 'trial ends'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Cursor',
    senderDomains: ['cursor.sh', 'cursor.com', 'mail.cursor.sh'],
    subjectPatterns: [/cursor.*subscription/i, /cursor.*pro/i, /welcome.*cursor/i],
    bodyKeywords: ['cursor', 'subscription', 'pro plan', 'billing', 'ai editor'],
    trialIndicators: ['free trial', 'trial period', 'trial ends'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Perplexity Pro',
    senderDomains: ['perplexity.ai', 'mail.perplexity.ai'],
    subjectPatterns: [/perplexity.*pro/i, /perplexity.*subscription/i, /welcome.*perplexity/i],
    bodyKeywords: ['perplexity', 'pro', 'subscription', 'billing'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Notion AI',
    senderDomains: ['notion.so', 'mail.notion.so', 'notion.com'],
    subjectPatterns: [/notion.*ai/i, /notion.*subscription/i, /notion.*billing/i],
    bodyKeywords: ['notion ai', 'subscription', 'billing', 'workspace'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Gemini Advanced',
    senderDomains: ['google.com', 'email.google.com'],
    subjectPatterns: [/gemini.*advanced/i, /google.*one.*ai/i, /gemini.*subscription/i],
    bodyKeywords: ['gemini advanced', 'google one', 'ai premium', 'subscription'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Runway',
    senderDomains: ['runwayml.com', 'runway.com'],
    subjectPatterns: [/runway.*subscription/i, /runway.*plan/i, /welcome.*runway/i],
    bodyKeywords: ['runway', 'subscription', 'standard', 'pro', 'unlimited', 'credits'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'ElevenLabs',
    senderDomains: ['elevenlabs.io', 'mail.elevenlabs.io'],
    subjectPatterns: [/elevenlabs.*subscription/i, /elevenlabs.*plan/i, /welcome.*elevenlabs/i],
    bodyKeywords: ['elevenlabs', 'subscription', 'voice', 'characters', 'billing'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Jasper AI',
    senderDomains: ['jasper.ai', 'mail.jasper.ai'],
    subjectPatterns: [/jasper.*subscription/i, /jasper.*plan/i, /welcome.*jasper/i],
    bodyKeywords: ['jasper', 'subscription', 'creator', 'teams', 'billing'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  {
    service: 'Copy.ai',
    senderDomains: ['copy.ai', 'mail.copy.ai'],
    subjectPatterns: [/copy\.ai.*subscription/i, /copy\.ai.*plan/i, /welcome.*copy\.ai/i],
    bodyKeywords: ['copy.ai', 'subscription', 'pro', 'billing'],
    trialIndicators: ['free trial', 'trial period'],
    priceExtractor: /\$(\d+\.?\d{0,2})\s*(?:\/month|per month|monthly)/i,
    dateExtractor: /(?:on|starting|renews)\s+(\w+\s+\d{1,2},?\s+\d{4})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP)/i,
  },
  // Generic pattern for unknown services - catches any subscription email
  {
    service: 'Unknown',
    senderDomains: [],
    subjectPatterns: [
      /subscription/i,
      /trial/i,
      /billing/i,
      /payment.*received/i,
      /payment.*confirmation/i,
      /receipt/i,
      /invoice/i,
      /renewal/i,
      /your.*plan/i,
      /membership/i,
      /upgrade/i,
      /welcome.*premium/i,
      /welcome.*pro/i,
      /thank.*for.*subscribing/i,
      /your.*account/i,
      /monthly.*statement/i,
      /charge.*processed/i,
    ],
    bodyKeywords: [
      'subscription',
      'trial',
      'billing',
      'monthly charge',
      'annual charge',
      'yearly charge',
      'recurring',
      'auto-renew',
      'renewal',
      'membership',
      'premium',
      'pro plan',
      'basic plan',
      'starter plan',
      'business plan',
      'enterprise',
      'invoice',
      'receipt',
      'payment method',
      'credit card',
      'charged',
      'billed',
      'next billing date',
      'renews on',
      'expires on',
      'cancel anytime',
      'manage subscription',
      'unsubscribe',
      '/month',
      '/year',
      'per month',
      'per year',
      'monthly fee',
      'annual fee',
    ],
    trialIndicators: ['free trial', 'trial period', 'trial ends', 'trial expires', 'days left', 'trial membership'],
    priceExtractor: /(?:\$|USD\s*|€|EUR\s*|£|GBP\s*|A\$|AUD\s*|C\$|CAD\s*|NZ\$|NZD\s*|¥|JPY\s*|CHF\s*)(\d+\.?\d{0,2})\s*(?:\/month|\/mo|per month|monthly|\/year|\/yr|per year|annually)?/i,
    dateExtractor: /(?:on|starting|ends|renews|expires|next billing|charged on|billed on)\s+(\w+\s+\d{1,2},?\s+\d{4}|\d{1,2}\/\d{1,2}\/\d{2,4}|\d{4}-\d{2}-\d{2})/i,
    currencyExtractor: /(\$|USD|€|EUR|£|GBP|AUD|CAD|NZD|JPY|CHF|A\$|C\$|NZ\$|¥)/i,
  },
]

export function getCurrencyCode(currencySymbol: string): string {
  const currencyMap: Record<string, string> = {
    '$': 'USD',
    'USD': 'USD',
    '€': 'EUR',
    'EUR': 'EUR',
    '£': 'GBP',
    'GBP': 'GBP',
    'A$': 'AUD',
    'AUD': 'AUD',
    'C$': 'CAD',
    'CAD': 'CAD',
    'NZ$': 'NZD',
    'NZD': 'NZD',
    '¥': 'JPY',
    'JPY': 'JPY',
    'CHF': 'CHF',
  }
  return currencyMap[currencySymbol] || 'USD'
}
