export type CancellationService = {
  slug: string
  name: string
  logo: string
  color: string
  monthlyPrice: string
  annualCost: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  difficultyReason: string
  whyPeopleForgot: string
  steps: string[]
  warnings: string[]
  alternatives?: string
  directCancelUrl?: string
}

export const cancellationServices: CancellationService[] = [
  {
    slug: 'netflix',
    name: 'Netflix',
    logo: '🎬',
    color: 'bg-red-700',
    monthlyPrice: '$15.49/mo',
    annualCost: '$185.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Netflix makes cancellation straightforward — no phone call required.',
    whyPeopleForgot: 'Shared family accounts make it easy to assume someone else is using it.',
    steps: [
      'Go to netflix.com and sign in to your account',
      'Click your profile icon in the top right corner',
      'Select "Account" from the dropdown menu',
      'Scroll down to the "Membership" section',
      'Click "Cancel Membership"',
      'Click "Finish Cancellation" to confirm',
      "You'll keep access until the end of your current billing period",
    ],
    warnings: [
      "Netflix will keep you subscribed until the end of your paid period — you won't get a refund",
      'Your watch history and profiles are saved for 10 months if you resubscribe',
      "If you were on a promotional price, you may lose it if you resubscribe",
    ],
    directCancelUrl: 'https://www.netflix.com/cancel',
  },
  {
    slug: 'spotify',
    name: 'Spotify',
    logo: '🎵',
    color: 'bg-green-700',
    monthlyPrice: '$11.99/mo',
    annualCost: '$143.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Spotify cancellation is online and takes under 2 minutes.',
    whyPeopleForgot: 'Spotify Free is available after cancelling, so the transition is invisible.',
    steps: [
      'Go to spotify.com and log in',
      'Click your profile name in the top right',
      'Select "Account"',
      'Under "Your plan", click "Change plan"',
      'Scroll to the bottom and click "Cancel Premium"',
      'Follow the prompts to confirm cancellation',
      'Your Premium access continues until the end of the billing period',
    ],
    warnings: [
      "You'll revert to Spotify Free (ad-supported) after cancellation — you don't lose your music library",
      'Downloaded music will no longer be available offline',
      'Any Spotify-linked devices will lose offline playback',
    ],
    directCancelUrl: 'https://www.spotify.com/account/subscription/cancel/',
  },
  {
    slug: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud',
    logo: '🎨',
    color: 'bg-red-900',
    monthlyPrice: '$54.99/mo',
    annualCost: '$659.88/yr',
    difficulty: 'Hard',
    difficultyReason:
      'Annual plans charge a 50% early termination fee if cancelled mid-year. Adobe also uses retention tactics during cancellation.',
    whyPeopleForgot: 'Free 7-day trials silently convert to annual commitments.',
    steps: [
      'Go to account.adobe.com and sign in',
      'Click "Manage plan" next to your Creative Cloud subscription',
      'Select "Cancel plan"',
      'Adobe will show you a retention offer — you can accept or decline',
      'If declining, click "Continue to cancel"',
      'Select a reason and confirm',
      'Note: If on an annual plan, check if an early termination fee applies',
    ],
    warnings: [
      'Annual plans billed monthly carry a 50% cancellation fee on remaining months if cancelled early',
      'Annual plans billed upfront may receive a partial refund for unused months',
      'Creative Cloud apps like Photoshop will enter read-only mode after cancellation',
      'Cloud storage content may be deleted 90 days after cancellation',
    ],
    alternatives: 'Affinity Photo/Designer (one-time purchase), Canva Pro, GIMP (free)',
  },
  {
    slug: 'apple-music',
    name: 'Apple Music',
    logo: '🍎',
    color: 'bg-pink-800',
    monthlyPrice: '$10.99/mo',
    annualCost: '$131.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Apple provides straightforward cancellation through Settings.',
    whyPeopleForgot: 'Often bundled with Apple One — people forget it is a separate charge.',
    steps: [
      'On iPhone/iPad: Go to Settings → [your name] → Subscriptions',
      'Tap "Apple Music"',
      'Tap "Cancel Subscription"',
      'Confirm cancellation',
      'On Mac: Open App Store → click your name → View Information → Subscriptions → Manage → Cancel',
    ],
    warnings: [
      'Cancelling removes access to the music library at the end of the billing period',
      'Downloaded music will no longer be available offline',
      "If you're cancelling Apple One to get Apple Music individually, check the math first — Apple One may be cheaper",
    ],
  },
  {
    slug: 'disney-plus',
    name: 'Disney+',
    logo: '✨',
    color: 'bg-blue-900',
    monthlyPrice: '$13.99/mo',
    annualCost: '$167.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Disney+ allows online cancellation with no retention friction.',
    whyPeopleForgot: 'Often started during a specific release (Star Wars, Marvel) and forgotten after.',
    steps: [
      'Go to disneyplus.com and sign in',
      'Click your profile icon',
      'Select "Account"',
      'Under "Subscription", click "Cancel Subscription"',
      'Select a reason and confirm',
      'Access continues until the end of your billing period',
    ],
    warnings: [
      'If billed through Apple, Amazon, or Google, you must cancel through that platform — not Disney+ directly',
      'Annual subscribers should check if they qualify for a prorated refund',
    ],
  },
  {
    slug: 'amazon-prime',
    name: 'Amazon Prime',
    logo: '📦',
    color: 'bg-yellow-700',
    monthlyPrice: '$14.99/mo',
    annualCost: '$139/yr',
    difficulty: 'Medium',
    difficultyReason:
      'Amazon uses multi-step confirmation flows and shows you everything you would lose to discourage cancellation.',
    whyPeopleForgot: 'Free trials offered at checkout are easy to click past without realising.',
    steps: [
      'Go to amazon.com and sign in',
      'Hover over "Account & Lists" → click "Account"',
      'Click "Prime Membership"',
      'Click "Manage membership"',
      'Select "End membership"',
      'Amazon will show a summary of what you lose — click "Continue to Cancel"',
      'Select "End Now" (immediate) or "End on [renewal date]"',
    ],
    warnings: [
      '"End Now" may offer a partial refund if you haven\'t used Prime benefits recently',
      '"End on renewal date" keeps Prime active until the next billing date',
      'Cancelling Prime also cancels Prime Video, Prime Music, and free delivery',
      'Amazon Subscribe & Save deliveries are separate and are not cancelled automatically',
    ],
    directCancelUrl: 'https://www.amazon.com/mc',
  },
  {
    slug: 'youtube-premium',
    name: 'YouTube Premium',
    logo: '▶️',
    color: 'bg-red-600',
    monthlyPrice: '$13.99/mo',
    annualCost: '$167.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'YouTube cancellation is straightforward through Google account settings.',
    whyPeopleForgot: 'Often started to remove ads during a binge, then forgotten.',
    steps: [
      'Go to youtube.com/paid_memberships or open YouTube app',
      'Click your profile photo → "Purchases and memberships"',
      'Click "Manage membership"',
      'Click "Deactivate" next to YouTube Premium',
      'Confirm deactivation',
    ],
    warnings: [
      'Cancelling YouTube Premium also cancels YouTube Music Premium',
      'Downloaded videos will no longer be available offline',
      'Ads will return immediately after the billing period ends',
    ],
    alternatives: 'uBlock Origin browser extension (blocks YouTube ads on desktop, free)',
  },
  {
    slug: 'duolingo-plus',
    name: 'Duolingo Plus',
    logo: '🦉',
    color: 'bg-green-600',
    monthlyPrice: '$6.99/mo',
    annualCost: '$83.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Duolingo cancellation is quick through the app or account settings.',
    whyPeopleForgot: 'Often started during a learning streak that later faded.',
    steps: [
      'Open the Duolingo app',
      'Tap your profile icon',
      'Tap "Super Duolingo" or "Duolingo Plus"',
      'Tap "Manage subscription"',
      'Follow the platform prompts (App Store or Google Play) to cancel',
      'Alternatively: cancel directly through your Apple or Google subscriptions page',
    ],
    warnings: [
      'Cancellation removes the ad-free experience and unlimited hearts',
      'Your streak and progress are saved on the free tier',
      "Duolingo doesn't send reminder emails before annual renewals",
    ],
  },
  {
    slug: 'audible',
    name: 'Audible',
    logo: '🎧',
    color: 'bg-orange-700',
    monthlyPrice: '$14.95/mo',
    annualCost: '$179.40/yr',
    difficulty: 'Medium',
    difficultyReason:
      'Audible uses a credit-based model that makes cancellation feel like losing money, and the cancel flow has multiple retention steps.',
    whyPeopleForgot: 'Monthly credits accumulate — people keep subscribing to "use up" credits they already paid for.',
    steps: [
      'Go to audible.com and sign in',
      'Click your name → "Account Details"',
      'Scroll down to "Cancel membership"',
      'Click "Cancel membership"',
      'Audible will offer a pause or discounted plan — decline if you want to cancel fully',
      'Select a reason and confirm cancellation',
    ],
    warnings: [
      'Use any remaining credits before cancelling — they expire on cancellation',
      'Books you\'ve already purchased remain in your library permanently',
      'Audible Originals you received free will remain accessible',
      "Audible is owned by Amazon — cancelling Audible doesn't affect Prime",
    ],
  },
  {
    slug: 'apple-one',
    name: 'Apple One',
    logo: '📱',
    color: 'bg-gray-700',
    monthlyPrice: '$22.95/mo',
    annualCost: '$275.40/yr',
    difficulty: 'Easy',
    difficultyReason: 'Apple One cancellation is straightforward but cancels all bundled services at once.',
    whyPeopleForgot: 'The bundle makes individual costs invisible — people forget how much they are paying.',
    steps: [
      'On iPhone/iPad: Settings → [your name] → Subscriptions',
      'Tap "Apple One"',
      'Tap "Cancel Subscription"',
      'Confirm',
      'All included services (Music, TV+, Arcade, iCloud) will end at the billing period',
    ],
    warnings: [
      'Cancelling Apple One cancels ALL included services simultaneously',
      'iCloud storage reverts to free 5GB — ensure you don\'t exceed this before cancelling',
      'Consider subscribing to individual services you actually use — it may be cheaper',
      'Family plan cancellation affects all family members',
    ],
  },
  {
    slug: 'hulu',
    name: 'Hulu',
    logo: '📺',
    color: 'bg-green-800',
    monthlyPrice: '$17.99/mo',
    annualCost: '$215.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Hulu offers online cancellation with minimal friction.',
    whyPeopleForgot: 'Often kept alongside Netflix or Disney+ out of habit.',
    steps: [
      'Go to hulu.com and sign in',
      'Click your name in the top right → "Account"',
      'Under "Your Subscription", click "Cancel"',
      'Hulu will offer a pause option — select "Continue to Cancel" if you want to cancel fully',
      'Select a reason and confirm',
    ],
    warnings: [
      'If Hulu is bundled with Disney+ or ESPN+, cancelling Hulu may affect the bundle price',
      'If billed through a third party (Apple, Roku), cancel through that platform',
      "Hulu's pause feature (up to 12 weeks) is worth considering if you'll come back",
    ],
  },
  {
    slug: 'canva-pro',
    name: 'Canva Pro',
    logo: '🖼️',
    color: 'bg-purple-700',
    monthlyPrice: '$14.99/mo',
    annualCost: '$119.99/yr',
    difficulty: 'Easy',
    difficultyReason: 'Canva Pro cancellation is online and quick.',
    whyPeopleForgot: 'Often started for a one-time project and kept on autopilot.',
    steps: [
      'Log in to canva.com',
      'Click your account name → "Account settings"',
      'Select "Billing & Teams"',
      'Click "Cancel plan"',
      'Confirm cancellation',
      'Pro features remain active until the end of the billing period',
    ],
    warnings: [
      'Pro-only elements in your designs will remain visible but locked after downgrade',
      'Team members on your workspace will lose Pro access',
      'Canva Free retains most core design features',
    ],
    alternatives: 'Canva Free (most features available), Figma Free tier, Adobe Express Free',
  },
  {
    slug: 'gym-membership',
    name: 'Gym Membership',
    logo: '🏋️',
    color: 'bg-slate-700',
    monthlyPrice: 'Varies by gym ($10–$60/mo typical)',
    annualCost: 'Varies by gym',
    difficulty: 'Hard',
    difficultyReason:
      'Most gyms require cancelling in person, by certified mail, or by fax — online cancellation is rarely offered, and many contracts lock you in for a minimum term.',
    whyPeopleForgot: 'Moving, a New Year resolution that faded, or switching to a different gym are the most common triggers — the membership outlives the motivation.',
    steps: [
      'Find your original signup contract or membership agreement (check email, or ask the front desk for a copy)',
      'Look for the cancellation clause — it will state the required method (in person, certified mail, fax) and notice period (often 30 days)',
      'If in-person cancellation is required, visit the specific location you signed up at, not just any franchise location',
      'If mailed cancellation is required, send it certified with return receipt so you have proof of delivery',
      'Include your full name, member ID, and requested cancellation date in writing',
      'Ask for (or request by email) written confirmation that your membership was cancelled and billing stopped',
      'Check your bank/card statement for the next 1-2 billing cycles to confirm the charge actually stopped',
    ],
    warnings: [
      'Annual contracts often carry an early termination fee if cancelled before the minimum term ends',
      'Some gyms only accept cancellation requests during a specific window each month — missing it delays cancellation by a full cycle',
      'Franchise locations are often independently owned — corporate customer service may not be able to process your cancellation',
      '"Freezing" or "pausing" a membership is not the same as cancelling — you may still be billed a reduced hold fee',
      'Verbal confirmation from staff is not enough — always get cancellation confirmed in writing',
    ],
  },
]
