export type CancellationService = {
  slug: string
  name: string
  logo: string
  color: string
  /** Omit when the current US price couldn't be confirmed from the vendor's own pricing page. */
  monthlyPrice?: string
  annualCost?: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  difficultyReason: string
  whyPeopleForgot: string
  steps: string[]
  warnings: string[]
  alternatives?: string
  directCancelUrl?: string
}

export const cancellationServices: CancellationService[] = [
  {
    slug: 'netflix',
    name: 'Netflix',
    logo: '🎬',
    color: 'bg-red-700',
    monthlyPrice: '$15.49/mo',
    annualCost: '$185.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Netflix makes cancellation straightforward — no phone call required.',
    whyPeopleForgot: 'Shared family accounts make it easy to assume someone else is using it.',
    steps: [
      'Go to netflix.com and sign in to your account',
      'Click your profile icon in the top right corner',
      'Select "Account" from the dropdown menu',
      'Scroll down to the "Membership" section',
      'Click "Cancel Membership"',
      'Click "Finish Cancellation" to confirm',
      "You'll keep access until the end of your current billing period",
    ],
    warnings: [
      "Netflix will keep you subscribed until the end of your paid period — you won't get a refund",
      'Your watch history and profiles are saved for 10 months if you resubscribe',
      "If you were on a promotional price, you may lose it if you resubscribe",
    ],
    directCancelUrl: 'https://www.netflix.com/cancel',
  },
  {
    slug: 'spotify',
    name: 'Spotify',
    logo: '🎵',
    color: 'bg-green-700',
    monthlyPrice: '$11.99/mo',
    annualCost: '$143.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Spotify cancellation is online and takes under 2 minutes.',
    whyPeopleForgot: 'Spotify Free is available after cancelling, so the transition is invisible.',
    steps: [
      'Go to spotify.com and log in',
      'Click your profile name in the top right',
      'Select "Account"',
      'Under "Your plan", click "Change plan"',
      'Scroll to the bottom and click "Cancel Premium"',
      'Follow the prompts to confirm cancellation',
      'Your Premium access continues until the end of the billing period',
    ],
    warnings: [
      "You'll revert to Spotify Free (ad-supported) after cancellation — you don't lose your music library",
      'Downloaded music will no longer be available offline',
      'Any Spotify-linked devices will lose offline playback',
    ],
    directCancelUrl: 'https://www.spotify.com/account/subscription/cancel/',
  },
  {
    slug: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud',
    logo: '🎨',
    color: 'bg-red-900',
    monthlyPrice: '$54.99/mo',
    annualCost: '$659.88/yr',
    difficulty: 'Hard',
    difficultyReason:
      'Annual plans charge a 50% early termination fee if cancelled mid-year. Adobe also uses retention tactics during cancellation.',
    whyPeopleForgot: 'Free 7-day trials silently convert to annual commitments.',
    steps: [
      'Go to account.adobe.com and sign in',
      'Click "Manage plan" next to your Creative Cloud subscription',
      'Select "Cancel plan"',
      'Adobe will show you a retention offer — you can accept or decline',
      'If declining, click "Continue to cancel"',
      'Select a reason and confirm',
      'Note: If on an annual plan, check if an early termination fee applies',
    ],
    warnings: [
      'Annual plans billed monthly carry a 50% cancellation fee on remaining months if cancelled early',
      'Annual plans billed upfront may receive a partial refund for unused months',
      'Creative Cloud apps like Photoshop will enter read-only mode after cancellation',
      'Cloud storage content may be deleted 90 days after cancellation',
    ],
    alternatives: 'Affinity Photo/Designer (one-time purchase), Canva Pro, GIMP (free)',
  },
  {
    slug: 'apple-music',
    name: 'Apple Music',
    logo: '🍎',
    color: 'bg-pink-800',
    monthlyPrice: '$10.99/mo',
    annualCost: '$131.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Apple provides straightforward cancellation through Settings.',
    whyPeopleForgot: 'Often bundled with Apple One — people forget it is a separate charge.',
    steps: [
      'On iPhone/iPad: Go to Settings → [your name] → Subscriptions',
      'Tap "Apple Music"',
      'Tap "Cancel Subscription"',
      'Confirm cancellation',
      'On Mac: Open App Store → click your name → View Information → Subscriptions → Manage → Cancel',
    ],
    warnings: [
      'Cancelling removes access to the music library at the end of the billing period',
      'Downloaded music will no longer be available offline',
      "If you're cancelling Apple One to get Apple Music individually, check the math first — Apple One may be cheaper",
    ],
  },
  {
    slug: 'disney-plus',
    name: 'Disney+',
    logo: '✨',
    color: 'bg-blue-900',
    monthlyPrice: '$13.99/mo',
    annualCost: '$167.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Disney+ allows online cancellation with no retention friction.',
    whyPeopleForgot: 'Often started during a specific release (Star Wars, Marvel) and forgotten after.',
    steps: [
      'Go to disneyplus.com and sign in',
      'Click your profile icon',
      'Select "Account"',
      'Under "Subscription", click "Cancel Subscription"',
      'Select a reason and confirm',
      'Access continues until the end of your billing period',
    ],
    warnings: [
      'If billed through Apple, Amazon, or Google, you must cancel through that platform — not Disney+ directly',
      'Annual subscribers should check if they qualify for a prorated refund',
    ],
  },
  {
    slug: 'amazon-prime',
    name: 'Amazon Prime',
    logo: '📦',
    color: 'bg-yellow-700',
    monthlyPrice: '$14.99/mo',
    annualCost: '$139/yr',
    difficulty: 'Medium',
    difficultyReason:
      'Amazon uses multi-step confirmation flows and shows you everything you would lose to discourage cancellation.',
    whyPeopleForgot: 'Free trials offered at checkout are easy to click past without realising.',
    steps: [
      'Go to amazon.com and sign in',
      'Hover over "Account & Lists" → click "Account"',
      'Click "Prime Membership"',
      'Click "Manage membership"',
      'Select "End membership"',
      'Amazon will show a summary of what you lose — click "Continue to Cancel"',
      'Select "End Now" (immediate) or "End on [renewal date]"',
    ],
    warnings: [
      '"End Now" may offer a partial refund if you haven\'t used Prime benefits recently',
      '"End on renewal date" keeps Prime active until the next billing date',
      'Cancelling Prime also cancels Prime Video, Prime Music, and free delivery',
      'Amazon Subscribe & Save deliveries are separate and are not cancelled automatically',
    ],
    directCancelUrl: 'https://www.amazon.com/mc',
  },
  {
    slug: 'youtube-premium',
    name: 'YouTube Premium',
    logo: '▶️',
    color: 'bg-red-600',
    monthlyPrice: '$13.99/mo',
    annualCost: '$167.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'YouTube cancellation is straightforward through Google account settings.',
    whyPeopleForgot: 'Often started to remove ads during a binge, then forgotten.',
    steps: [
      'Go to youtube.com/paid_memberships or open YouTube app',
      'Click your profile photo → "Purchases and memberships"',
      'Click "Manage membership"',
      'Click "Deactivate" next to YouTube Premium',
      'Confirm deactivation',
    ],
    warnings: [
      'Cancelling YouTube Premium also cancels YouTube Music Premium',
      'Downloaded videos will no longer be available offline',
      'Ads will return immediately after the billing period ends',
    ],
    alternatives: 'uBlock Origin browser extension (blocks YouTube ads on desktop, free)',
  },
  {
    slug: 'duolingo-plus',
    name: 'Duolingo Plus',
    logo: '🦉',
    color: 'bg-green-600',
    monthlyPrice: '$6.99/mo',
    annualCost: '$83.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Duolingo cancellation is quick through the app or account settings.',
    whyPeopleForgot: 'Often started during a learning streak that later faded.',
    steps: [
      'Open the Duolingo app',
      'Tap your profile icon',
      'Tap "Super Duolingo" or "Duolingo Plus"',
      'Tap "Manage subscription"',
      'Follow the platform prompts (App Store or Google Play) to cancel',
      'Alternatively: cancel directly through your Apple or Google subscriptions page',
    ],
    warnings: [
      'Cancellation removes the ad-free experience and unlimited hearts',
      'Your streak and progress are saved on the free tier',
      "Duolingo doesn't send reminder emails before annual renewals",
    ],
  },
  {
    slug: 'audible',
    name: 'Audible',
    logo: '🎧',
    color: 'bg-orange-700',
    monthlyPrice: '$14.95/mo',
    annualCost: '$179.40/yr',
    difficulty: 'Medium',
    difficultyReason:
      'Audible uses a credit-based model that makes cancellation feel like losing money, and the cancel flow has multiple retention steps.',
    whyPeopleForgot: 'Monthly credits accumulate — people keep subscribing to "use up" credits they already paid for.',
    steps: [
      'Go to audible.com and sign in',
      'Click your name → "Account Details"',
      'Scroll down to "Cancel membership"',
      'Click "Cancel membership"',
      'Audible will offer a pause or discounted plan — decline if you want to cancel fully',
      'Select a reason and confirm cancellation',
    ],
    warnings: [
      'Use any remaining credits before cancelling — they expire on cancellation',
      'Books you\'ve already purchased remain in your library permanently',
      'Audible Originals you received free will remain accessible',
      "Audible is owned by Amazon — cancelling Audible doesn't affect Prime",
    ],
  },
  {
    slug: 'apple-one',
    name: 'Apple One',
    logo: '📱',
    color: 'bg-gray-700',
    monthlyPrice: '$22.95/mo',
    annualCost: '$275.40/yr',
    difficulty: 'Easy',
    difficultyReason: 'Apple One cancellation is straightforward but cancels all bundled services at once.',
    whyPeopleForgot: 'The bundle makes individual costs invisible — people forget how much they are paying.',
    steps: [
      'On iPhone/iPad: Settings → [your name] → Subscriptions',
      'Tap "Apple One"',
      'Tap "Cancel Subscription"',
      'Confirm',
      'All included services (Music, TV+, Arcade, iCloud) will end at the billing period',
    ],
    warnings: [
      'Cancelling Apple One cancels ALL included services simultaneously',
      'iCloud storage reverts to free 5GB — ensure you don\'t exceed this before cancelling',
      'Consider subscribing to individual services you actually use — it may be cheaper',
      'Family plan cancellation affects all family members',
    ],
  },
  {
    slug: 'hulu',
    name: 'Hulu',
    logo: '📺',
    color: 'bg-green-800',
    monthlyPrice: '$17.99/mo',
    annualCost: '$215.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Hulu offers online cancellation with minimal friction.',
    whyPeopleForgot: 'Often kept alongside Netflix or Disney+ out of habit.',
    steps: [
      'Go to hulu.com and sign in',
      'Click your name in the top right → "Account"',
      'Under "Your Subscription", click "Cancel"',
      'Hulu will offer a pause option — select "Continue to Cancel" if you want to cancel fully',
      'Select a reason and confirm',
    ],
    warnings: [
      'If Hulu is bundled with Disney+ or ESPN+, cancelling Hulu may affect the bundle price',
      'If billed through a third party (Apple, Roku), cancel through that platform',
      "Hulu's pause feature (up to 12 weeks) is worth considering if you'll come back",
    ],
  },
  {
    slug: 'canva-pro',
    name: 'Canva Pro',
    logo: '🖼️',
    color: 'bg-purple-700',
    monthlyPrice: '$14.99/mo',
    annualCost: '$119.99/yr',
    difficulty: 'Easy',
    difficultyReason: 'Canva Pro cancellation is online and quick.',
    whyPeopleForgot: 'Often started for a one-time project and kept on autopilot.',
    steps: [
      'Log in to canva.com',
      'Click your account name → "Account settings"',
      'Select "Billing & Teams"',
      'Click "Cancel plan"',
      'Confirm cancellation',
      'Pro features remain active until the end of the billing period',
    ],
    warnings: [
      'Pro-only elements in your designs will remain visible but locked after downgrade',
      'Team members on your workspace will lose Pro access',
      'Canva Free retains most core design features',
    ],
    alternatives: 'Canva Free (most features available), Figma Free tier, Adobe Express Free',
  },
  {
    slug: 'gym-membership',
    name: 'Gym Membership',
    logo: '🏋️',
    color: 'bg-slate-700',
    monthlyPrice: 'Varies by gym ($10–$60/mo typical)',
    annualCost: 'Varies by gym',
    difficulty: 'Hard',
    difficultyReason:
      'Most gyms require cancelling in person, by certified mail, or by fax — online cancellation is rarely offered, and many contracts lock you in for a minimum term.',
    whyPeopleForgot: 'Moving, a New Year resolution that faded, or switching to a different gym are the most common triggers — the membership outlives the motivation.',
    steps: [
      'Find your original signup contract or membership agreement (check email, or ask the front desk for a copy)',
      'Look for the cancellation clause — it will state the required method (in person, certified mail, fax) and notice period (often 30 days)',
      'If in-person cancellation is required, visit the specific location you signed up at, not just any franchise location',
      'If mailed cancellation is required, send it certified with return receipt so you have proof of delivery',
      'Include your full name, member ID, and requested cancellation date in writing',
      'Ask for (or request by email) written confirmation that your membership was cancelled and billing stopped',
      'Check your bank/card statement for the next 1-2 billing cycles to confirm the charge actually stopped',
    ],
    warnings: [
      'Annual contracts often carry an early termination fee if cancelled before the minimum term ends',
      'Some gyms only accept cancellation requests during a specific window each month — missing it delays cancellation by a full cycle',
      'Franchise locations are often independently owned — corporate customer service may not be able to process your cancellation',
      '"Freezing" or "pausing" a membership is not the same as cancelling — you may still be billed a reduced hold fee',
      'Verbal confirmation from staff is not enough — always get cancellation confirmed in writing',
    ],
  },
  {
    slug: 'siriusxm',
    name: 'SiriusXM',
    logo: '📡',
    color: 'bg-blue-800',
    monthlyPrice: '$10.99–$25.99/mo (varies by plan)',
    annualCost: '$131.88–$311.88/yr',
    difficulty: 'Hard',
    difficultyReason:
      'SiriusXM rarely offers a simple online cancel button — the "Cancel" flow usually opens a retention chat or requires a phone call, and reps are trained to offer discounts before processing the cancellation.',
    whyPeopleForgot: 'A free trial bundled with a new or used car purchase is the most common trigger — it auto-converts to paid after a few months and keeps billing the card on file.',
    steps: [
      'Log in to your account at siriusxm.com',
      'Go to "My Account" and look for "Manage Subscription" or "Cancel"',
      'If a live chat opens instead of a direct cancel button, tell the agent clearly you want to cancel, not pause or discount',
      'Expect at least one retention offer (a discounted rate) — decline it if you actually want to cancel',
      "If chat isn't available or won't cancel you, call subscriber services at 1-866-635-2349 and request cancellation directly",
      'Ask for a confirmation number or email confirming the cancellation date',
      'Check your next 1-2 statements to confirm billing actually stopped',
    ],
    warnings: [
      'Reps are trained to offer 2-3 rounds of discounts before processing a cancellation — stay firm if you want it fully cancelled',
      "Car-installed radios may still display \"SiriusXM Ready\" or show signal after cancelling — that's normal and doesn't mean you're still billed",
      'Free trials from a car purchase convert to paid automatically unless cancelled before the trial end date',
      'Streaming-only and satellite hardware plans are managed separately — cancelling one does not cancel the other if you have both',
      'Refunds for the remaining prepaid period are rarely offered automatically — ask explicitly if you paid annually',
    ],
  },
  {
    slug: 'linkedin-premium',
    name: 'LinkedIn Premium',
    logo: '💼',
    color: 'bg-blue-800',
    monthlyPrice: '$29.99–$59.99/mo',
    annualCost: '$239.88–$719.88/yr',
    difficulty: 'Medium',
    difficultyReason:
      'The cancellation flow itself is simple, but annual plans renew with no advance warning email for most users, so the difficulty is catching it before the renewal charge, not the cancel steps.',
    whyPeopleForgot:
      'Signed up for a free trial to send InMail or see who viewed their profile, then the annual plan auto-renewed a year later with no reminder.',
    steps: [
      'Go to linkedin.com and click "Me" → "Access My LinkedIn" → "Settings & Privacy"',
      'Click "Access my account" → "Manage subscriptions and payments" (or go directly to premium.linkedin.com/manage)',
      'Select the active Premium plan',
      'Click "Cancel subscription"',
      'Work through the retention offer if shown, then confirm cancellation',
      'Check your email for a cancellation confirmation',
    ],
    warnings: [
      'No proration — cancelling does not refund the current billing period, but you keep Premium features until it ends',
      'Annual plans renew for the full year with no advance notice email for most accounts',
      'Cancelling removes InMail credits and Premium analytics immediately upon expiration, not immediately upon cancelling',
    ],
    alternatives: 'Free LinkedIn account, Sales Navigator (if InMail is the only feature used), manual networking',
  },
  {
    slug: 'semrush',
    name: 'Semrush',
    logo: '📈',
    color: 'bg-orange-700',
    monthlyPrice: '$139.95–$499.95/mo',
    annualCost: '$1,679.40–$5,999.40/yr',
    difficulty: 'Hard',
    difficultyReason:
      'A self-serve cancel flow exists but routes through a multi-step retention funnel, and some users report the online flow does not fully cancel without also confirming through live chat with support.',
    whyPeopleForgot:
      'Signed up for a free trial or a single SEO audit and let it roll into a monthly or annual plan that kept renewing after the project ended.',
    steps: [
      'Log in and click your account icon → "Subscription info"',
      'Click "Cancel subscription"',
      'Work through the cancellation survey and any discount/pause offers presented before the cancel confirms',
      'If the online flow stalls or does not show a final confirmation, open live chat and explicitly request cancellation and written confirmation',
      'Save the confirmation email or chat transcript as proof',
    ],
    warnings: [
      'Annual plans are billed upfront — cancelling stops future renewals but typically does not refund the current term',
      'Some users report being billed after believing they cancelled through the self-serve flow alone — always get written confirmation',
      'Downgrading to a lower tier is a separate action from cancelling; make sure you complete full cancellation if that is the goal',
    ],
    alternatives: 'Ahrefs, Ubersuggest, Google Search Console + free keyword tools',
  },
  {
    slug: 'godaddy',
    name: 'GoDaddy',
    logo: '🌐',
    color: 'bg-teal-700',
    monthlyPrice: 'Varies by product ($5–$30/mo typical for hosting)',
    annualCost: 'Varies by domain/hosting plan',
    difficulty: 'Medium',
    difficultyReason:
      'Cancelling a product and turning off auto-renew are two separate settings, and renewal billing starts 30–45 days before expiration, so people cancel too late if they only cancel the product.',
    whyPeopleForgot:
      'Bought a domain or hosting plan for a one-off project and assumed letting it "expire" would stop billing, not realizing auto-renew charges before expiration.',
    steps: [
      'Log in and go to "My Products"',
      'For a domain: open the domain, go to domain settings, and toggle off "Auto Renew" specifically — cancelling the product alone does not stop this',
      'For hosting/websites: select the plan, then click "Cancel" under Renewals & Billing',
      'Confirm cancellation',
      'Check "My Products" afterward to verify the item shows as non-renewing',
    ],
    warnings: [
      'Turning off auto-renew is a separate step from cancelling — missing it is the most common reason people get charged again',
      'Renewal charges are billed 30–45 days before the expiration date, so disable auto-renew well before then',
      'Domain cancellation does not release the domain name immediately; it typically enters an expiration/redemption period first',
      'Refunds for hosting are prorated only within a limited window (often 30–45 days of purchase) — check the current refund policy before assuming a refund applies',
    ],
    alternatives: 'Cloudflare Registrar (domains, at-cost renewal), Namecheap, Netlify/Vercel (hosting)',
  },
  {
    slug: 'hbo-max',
    name: 'HBO Max',
    logo: '📺',
    color: 'bg-purple-700',
    monthlyPrice: '$18.49/mo',
    annualCost: '$221.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'HBO Max has a self-serve web flow with a single "Cancel Your Subscription" button — as long as you are billed by HBO Max directly.',
    whyPeopleForgot: 'It often arrives through a bundle or a third-party billing route (Amazon, Roku, Hulu, a phone or TV provider), so the charge never shows on the HBO Max account itself.',
    steps: [
      'Go to hbomax.com/subscription and sign in',
      'Or, on a computer, select your profile, then "Subscription" (mobile/tablet: profile > Subscription; TV: Settings icon lower left > Subscription)',
      'Check the billing provider shown at the top of the screen — these steps apply only if it is HBO Max direct',
      'Select "Cancel Your Subscription"',
      'Confirm the cancellation and note the expiration date shown',
      'Look for the cancellation confirmation email',
    ],
    warnings: [
      'Deleting the app does not cancel your subscription — it renews until you cancel',
      'HBO Max advises cancelling at least 24 hours before your next billing date to avoid another charge',
      'You keep streaming until the end of the current billing period, and can resume from Subscription > "Resume Your Subscription"',
      'Cancelling the base subscription also cancels add-ons such as the Extra Member add-on (unused time is refunded pro rata)',
      "Billed through Apple, Google Play, Amazon, Roku, Samsung, Xumo, Hulu, Prime Video, Sling, Spectrum, Verizon, Xfinity or YouTube? Cancel in that provider's account instead",
      'Prices shown are the Standard (ad-free) plan on hbomax.com as of September 2026; the annual plan works out cheaper than 12 monthly payments',
    ],
    directCancelUrl: 'https://www.hbomax.com/subscription',
  },
  {
    slug: 'expressvpn',
    name: 'ExpressVPN',
    logo: '🔒',
    color: 'bg-red-600',
    difficulty: 'Easy',
    difficultyReason: 'ExpressVPN has a self-serve "Cancel subscription" button in its web portal, but you cannot cancel from inside the app.',
    whyPeopleForgot: 'Long intro terms mean the renewal charge arrives years after signup, and you cannot cancel from the app you actually use.',
    steps: [
      'Go to portal.expressvpn.com/my-subscription and sign in',
      'Under "Automatic renewal", click "Cancel subscription"',
      'Follow the on-screen prompts to confirm',
      'Do this at least 24 hours before your next billing date (or before a free trial ends) to avoid a charge',
    ],
    warnings: [
      'You cannot cancel from inside the ExpressVPN app — use the website or the app store you subscribed through',
      'You keep access until the end of the current billing term',
      'Cancelling is separate from refunding: the 30-day money-back guarantee is for first-time customers only and is requested via Account & Billing > Payment History, or by contacting support',
      'App Store and Google Play purchases are not covered by the guarantee — refunds are up to Apple or Google',
      'Promotional or 2-year intro pricing applies only to the first term; the plan renews at the standard rate shown at checkout',
      'iPhone: Settings > your name > Subscriptions > ExpressVPN > Cancel. Android: Play Store > profile > Payments & subscriptions > Subscriptions > ExpressVPN > Cancel',
    ],
    directCancelUrl: 'https://portal.expressvpn.com/my-subscription',
  },
  {
    slug: '1password',
    name: '1Password',
    logo: '🔑',
    color: 'bg-blue-600',
    monthlyPrice: '$3.99/mo',
    annualCost: '$47.88/yr',
    difficulty: 'Easy',
    difficultyReason: 'Billing > Cancel subscription on 1Password.com — though the button can be hidden below the fold.',
    whyPeopleForgot: 'Annual billing at a low monthly-equivalent price is easy to forget until the renewal charge lands.',
    steps: [
      'Sign in to your account on 1Password.com',
      'Select "Billing" in the sidebar',
      'Select "Cancel subscription" (you may need to scroll to find it)',
      'Follow the onscreen instructions to confirm',
      'Before your billing period ends, sign in and export your data',
    ],
    warnings: [
      'When the billing period ends your account is frozen — export your data before then and do not delete the account',
      'No refunds for past charges or remaining time; there is no charge if you cancel during a free trial',
      'If your last payment failed, Billing is hidden: add a new payment method first, or email 1Password support to cancel',
      'Started through an in-app purchase on Apple or Android? Cancel with Apple or Google instead',
      'Business accounts managed by 1Password should contact their account manager',
      'Individual is $3.99/mo billed annually; new customers on 1Password.com may get a first-year promotional price',
    ],
    directCancelUrl: 'https://support.1password.com/manage-subscription/',
  },
  {
    slug: 'nordvpn',
    name: 'NordVPN',
    logo: '🛡️',
    color: 'bg-blue-700',
    difficulty: 'Easy',
    difficultyReason: 'Cancelling auto-renewal is a self-serve toggle in your Nord Account — getting a refund is a separate request through live chat.',
    whyPeopleForgot: 'Multi-year plans are paid upfront, so there is no recurring charge to remind you until the renewal lands.',
    steps: [
      'Log in to your Nord Account at my.nordaccount.com',
      'Open the "Billing" tab',
      'Click "Cancel" next to "Auto-renewal"',
      'Select "Cancel auto-renewal"',
      'Check that "Auto-renewal" now shows OFF',
      'Look for the confirmation email from NordVPN',
    ],
    warnings: [
      'Cancelling auto-renewal stops future charges but does not refund anything — a refund is a separate request through NordVPN live chat',
      'The 30-day money-back guarantee applies only to the initial payment on direct purchases, not to renewals',
      'Renewals are charged at the renewal price, which can be higher than the price you first paid',
      'Bought through Google Play, the Apple App Store or Amazon? Cancel with that store — NordVPN cannot refund App Store payments',
    ],
    directCancelUrl: 'https://my.nordaccount.com/',
  },
  {
    slug: 'grammarly',
    name: 'Grammarly',
    logo: '✍️',
    color: 'bg-green-600',
    difficulty: 'Easy',
    difficultyReason: 'Grammarly has a self-serve "Cancel Subscription" button on the web account page — no chat or phone call required.',
    whyPeopleForgot: 'A 7-day Pro trial that converts into auto-renewing annual billing means the charge arrives long after you signed up.',
    steps: [
      'Sign in to your Grammarly account',
      'Click the "Account" tab in the left sidebar',
      'Go to "Your account" > "Subscription"',
      'Scroll to the bottom of the page and click "Cancel Subscription"',
      'Click "Continue" in the confirmation window',
      'Select a cancellation reason',
      'Click "Cancel Subscription" to confirm',
    ],
    warnings: [
      'Cancelling stops auto-renewal, but you keep paid features until the end of the current subscription period',
      'Refunds are issued only where required by law; Apple purchases must request refunds from Apple',
      "Bought through Apple? Use Apple's subscription page instead",
      'Deleting your account is a separate process — it does not cancel billing on its own',
    ],
    directCancelUrl: 'https://account.grammarly.com/subscription',
  },
  {
    slug: 'notion',
    name: 'Notion',
    logo: '📝',
    color: 'bg-gray-700',
    difficulty: 'Easy',
    difficultyReason: 'Notion has no separate "cancel" button — you downgrade the workspace to the Free plan in Settings > Billing.',
    whyPeopleForgot: 'Paid plans are per workspace and easy to leave running after a project or team winds down.',
    steps: [
      'In the sidebar, click "Settings"',
      'Click "Billing"',
      'Click "Change plan"',
      'Select the "Free" plan',
      'Click "Continue"',
      'Give feedback if asked',
      'Click "Downgrade" and check the confirmation showing the date your current plan ends',
    ],
    warnings: [
      'Your current plan stays active until its expiration date — the downgrade takes effect at renewal',
      'Only workspace owners can see Settings > Billing, and plans apply per workspace',
      'On Free, multi-user workspaces are limited to 1,000 blocks (single-user workspaces stay unlimited), version history drops to 7 days, and file uploads are capped at 5 MB',
      'Custom Agents are switched off rather than deleted; existing automations continue but become view-only',
    ],
    directCancelUrl: 'https://www.notion.com/help/plan-downgrade',
  },
  {
    slug: 'dropbox',
    name: 'Dropbox',
    logo: '📦',
    color: 'bg-blue-600',
    difficulty: 'Easy',
    difficultyReason: 'Dropbox has a self-serve "Cancel plan" button in Manage account.',
    whyPeopleForgot: 'Storage plans renew silently in the background, and people stop thinking about them once their files have synced.',
    steps: [
      'Log in to dropbox.com',
      'Click your avatar in the bottom-left corner',
      'Click "Manage account"',
      'Click "Cancel plan" at the bottom of the page',
      'Select a reason for cancelling',
      'Click "Continue canceling" or "Confirm change" and follow the prompts',
      'Look for the confirmation email from no-reply@dropbox.com ("Dropbox Plan will not renew")',
    ],
    warnings: [
      'Your plan changes to free Dropbox Basic (2 GB) at the end of the current billing cycle — no further charges',
      'If you have more than 2 GB stored, Dropbox may block syncing, uploading, sharing or moving files, and prolonged overage could lead to file deletion — download or trim files first',
      'In most cases payments are not refundable; customers in the EU, UK and Turkey can request a refund within 14 days of purchase',
      'Bought through an app store? Cancel with Apple or Google — if you cannot see "Cancel plan", this is likely why',
    ],
    directCancelUrl: 'https://help.dropbox.com/plans/downgrade-dropbox-individual-plans',
  },
  {
    slug: 'microsoft-365',
    name: 'Microsoft 365',
    logo: '💼',
    color: 'bg-orange-600',
    difficulty: 'Easy',
    difficultyReason: 'Cancelling is self-serve from the Services page of your Microsoft account.',
    whyPeopleForgot: 'It is often bundled with a new PC or auto-renewed annually, so charges are infrequent and easy to miss.',
    steps: [
      'Go to account.microsoft.com/services/microsoft365 and sign in with the Microsoft account you bought it with',
      'Select "Cancel subscription" (it may say "Upgrade or Cancel")',
      'Review the cancellation details shown',
      'Choose "I don\'t want my subscription"',
      'To stop renewal only, go to account.microsoft.com/services, select "Manage" then "Turn off recurring billing"',
      'If you see "Turn on recurring billing" instead, the subscription is already set to expire',
    ],
    warnings: [
      'With recurring billing off, you and anyone you share Family with keep access until the expiry date',
      'After it ends, storage drops to 5 GB of OneDrive cloud storage plus 15 GB for Outlook.com; if you are over the limits you cannot upload new files or send and receive Outlook.com email, and after 6 months unused files may be deleted',
      'Not every cancellation qualifies for a refund — complete the cancellation to see your eligibility (prorated refunds are listed for only some countries; the US is not among them)',
      'Bought through Apple, Google Play or a retailer such as Amazon? Cancel with them instead',
    ],
    directCancelUrl: 'https://account.microsoft.com/services/microsoft365',
  },
  {
    slug: 'google-one',
    name: 'Google One',
    logo: '☁️',
    color: 'bg-blue-500',
    difficulty: 'Easy',
    difficultyReason: 'Google One is a three-click cancellation on one.google.com.',
    whyPeopleForgot: 'It is a cheap storage add-on that gets taken up when a phone or Gmail nears the 15 GB limit, then forgotten.',
    steps: [
      'On a computer, go to one.google.com',
      'Select "Settings"',
      'Select "Cancel membership"',
      'Click "Cancel" to confirm',
    ],
    warnings: [
      'Your Google Account keeps up to 15 GB of storage at no charge after you cancel',
      'Over the free limit you cannot send or receive Gmail, upload to Drive, or back up to Google Photos; existing files stay accessible',
      'The downgrade takes effect at the end of the current billing cycle, and you can rejoin any time',
      'Billed through a mobile carrier or other third party? Cancel with that provider — not in Google One',
    ],
    directCancelUrl: 'https://one.google.com/',
  },
]
