export type OpenSourceAlternative = {
  name: string
  description: string
  websiteUrl: string
  sourceCodeUrl: string
  stars: number
  license: string
  selfHosted: boolean
  installInstructions?: string
}

export type AlternativeCategory = {
  slug: string
  category: string
  emoji: string
  paidServices: string[]
  alternatives: OpenSourceAlternative[]
}

export const alternativeCategories: AlternativeCategory[] = [
  {
    slug: 'media-streaming',
    category: 'Media Streaming',
    emoji: '🎬',
    paidServices: ['Netflix', 'Disney+', 'Max', 'Hulu', 'Paramount+', 'Peacock', 'Crunchyroll', 'Amazon Prime Video', 'YouTube Premium'],
    alternatives: [
      {
        name: 'Jellyfin',
        description: 'Free media system that lets you stream your own movie, TV, and music collection from any device.',
        websiteUrl: 'https://jellyfin.org',
        sourceCodeUrl: 'https://github.com/jellyfin/jellyfin',
        stars: 36000,
        license: 'GPL-2.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name jellyfin -p 8096:8096 -v /path/to/config:/config -v /path/to/media:/media jellyfin/jellyfin:latest`. See jellyfin.org/docs/general/installation for reverse proxy and hardware transcoding setup.',
      },
      {
        name: 'Invidious',
        description: 'Lightweight YouTube front-end with no ads, no tracking, and no Google account required.',
        websiteUrl: 'https://invidious.io',
        sourceCodeUrl: 'https://github.com/iv-org/invidious',
        stars: 16000,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Ships an official `docker-compose.yml` (bundles Postgres) in the repo root — clone github.com/iv-org/invidious, copy `docker-compose.yml.example`, and run `docker compose up -d`. Full instructions at github.com/iv-org/invidious/wiki/Installation.',
      },
      {
        name: 'PeerTube',
        description: 'Decentralised, federated video platform — like a community-run YouTube.',
        websiteUrl: 'https://joinpeertube.org',
        sourceCodeUrl: 'https://github.com/Chocobozzz/PeerTube',
        stars: 13000,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Officially deployed via Docker Compose: download the sample `docker-compose.yml` and `.env` from the `support/docker/production` directory of the PeerTube repo, fill in your domain/SMTP settings, then run `docker compose up -d`. See docs.joinpeertube.org/install/docker.',
      },
    ],
  },
  {
    slug: 'music-streaming',
    category: 'Music Streaming',
    emoji: '🎵',
    paidServices: ['Spotify', 'Apple Music', 'Tidal', 'YouTube Music'],
    alternatives: [
      {
        name: 'Navidrome',
        description: 'Modern, fast self-hosted music server compatible with Subsonic and Airsonic clients.',
        websiteUrl: 'https://www.navidrome.org',
        sourceCodeUrl: 'https://github.com/navidrome/navidrome',
        stars: 12000,
        license: 'GPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name navidrome -p 4533:4533 -v /path/data:/data -v /path/music:/music:ro deluan/navidrome:latest`. See navidrome.org/docs/installation/docker for a Compose example.',
      },
      {
        name: 'Funkwhale',
        description: 'Federated music streaming and sharing platform built for communities.',
        websiteUrl: 'https://funkwhale.audio',
        sourceCodeUrl: 'https://dev.funkwhale.audio/funkwhale/funkwhale',
        stars: 1600,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Recommended install is Docker Compose (multiple services: api, celery worker, nginx, Postgres, Redis) — follow the step-by-step guide at docs.funkwhale.audio/administrator/installation/docker.html to generate your `.env` and `docker-compose.yml`.',
      },
    ],
  },
  {
    slug: 'cloud-storage',
    category: 'Cloud Storage',
    emoji: '☁️',
    paidServices: ['Dropbox', 'Google One', 'iCloud+', 'OneDrive'],
    alternatives: [
      {
        name: 'Nextcloud',
        description: 'Full Dropbox/Google Workspace replacement — files, calendar, contacts, notes, video calls.',
        websiteUrl: 'https://nextcloud.com',
        sourceCodeUrl: 'https://github.com/nextcloud/server',
        stars: 28000,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d -p 8080:80 -v /path/nextcloud:/var/www/html nextcloud:latest`. For production use, pair it with a separate database container (MariaDB/Postgres) as shown in the docs at hub.docker.com/_/nextcloud.',
      },
      {
        name: 'Syncthing',
        description: 'Continuous, peer-to-peer file sync between your devices. No cloud middleman.',
        websiteUrl: 'https://syncthing.net',
        sourceCodeUrl: 'https://github.com/syncthing/syncthing',
        stars: 66000,
        license: 'MPL-2.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name syncthing -p 8384:8384 -p 22000:22000/tcp -p 22000:22000/udp -p 21027:21027/udp -v /path/config:/var/syncthing syncthing/syncthing`. See docs.syncthing.net/users/docker.html.',
      },
    ],
  },
  {
    slug: 'design-creative',
    category: 'Design & Creative',
    emoji: '🎨',
    paidServices: ['Adobe Creative Cloud', 'Canva Pro', 'Figma', 'Sketch'],
    alternatives: [
      {
        name: 'GIMP',
        description: 'Mature raster image editor — the open-source counterpart to Photoshop.',
        websiteUrl: 'https://www.gimp.org',
        sourceCodeUrl: 'https://gitlab.gnome.org/GNOME/gimp',
        stars: 1800,
        license: 'GPL-3.0',
        selfHosted: false,
      },
      {
        name: 'Inkscape',
        description: 'Professional vector graphics editor — an open alternative to Illustrator.',
        websiteUrl: 'https://inkscape.org',
        sourceCodeUrl: 'https://gitlab.com/inkscape/inkscape',
        stars: 2200,
        license: 'GPL-2.0',
        selfHosted: false,
      },
      {
        name: 'Kdenlive',
        description: 'Non-linear video editor with multi-track timelines, effects, and proxy editing.',
        websiteUrl: 'https://kdenlive.org',
        sourceCodeUrl: 'https://invent.kde.org/multimedia/kdenlive',
        stars: 3100,
        license: 'GPL-3.0',
        selfHosted: false,
      },
      {
        name: 'Penpot',
        description: 'Open-source design and prototyping platform — the Figma replacement.',
        websiteUrl: 'https://penpot.app',
        sourceCodeUrl: 'https://github.com/penpot/penpot',
        stars: 34000,
        license: 'MPL-2.0',
        selfHosted: true,
        installInstructions: 'Deployed via Docker Compose (frontend, backend, exporter, Postgres, Redis, MinIO/S3 services). Follow the official self-hosting guide at penpot.app/docs/self-hosting to fetch the `docker-compose.yaml` and run `docker compose up -d`.',
      },
      {
        name: 'Darktable',
        description: 'RAW photo workflow and non-destructive editor — a Lightroom alternative.',
        websiteUrl: 'https://www.darktable.org',
        sourceCodeUrl: 'https://github.com/darktable-org/darktable',
        stars: 11000,
        license: 'GPL-3.0',
        selfHosted: false,
      },
    ],
  },
  {
    slug: 'productivity',
    category: 'Productivity & Notes',
    emoji: '📝',
    paidServices: ['Notion', 'Evernote', 'Todoist', 'Microsoft 365', 'Grammarly'],
    alternatives: [
      {
        name: 'AppFlowy',
        description: 'Notion-style workspace for wikis, projects, and docs — all open source.',
        websiteUrl: 'https://appflowy.io',
        sourceCodeUrl: 'https://github.com/AppFlowy-IO/AppFlowy',
        stars: 58000,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'The AppFlowy app itself is a desktop client; for self-hosted sync, deploy AppFlowy Cloud via its official `docker-compose.yml` (see github.com/AppFlowy-IO/AppFlowy-Cloud) and point the desktop client at your server URL.',
      },
      {
        name: 'Outline',
        description: 'Fast, collaborative team knowledge base and wiki.',
        websiteUrl: 'https://www.getoutline.com',
        sourceCodeUrl: 'https://github.com/outline/outline',
        stars: 29000,
        license: 'BSL-1.1',
        selfHosted: true,
        installInstructions: 'Runs via Docker Compose (needs Postgres, Redis, and S3-compatible storage). Copy the repo\'s `docker-compose.yml` and `.env.sample`, fill in the required secrets, then run `docker compose up`. Full guide at docs.getoutline.com/s/hosting.',
      },
      {
        name: 'Joplin',
        description: 'Cross-platform note-taking app with end-to-end encryption and sync.',
        websiteUrl: 'https://joplinapp.org',
        sourceCodeUrl: 'https://github.com/laurent22/joplin',
        stars: 47000,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'For synced notes across devices, self-host Joplin Server via the official image: `docker run -d -p 22300:22300 joplin/server:latest` (requires a Postgres database, configured via env vars). See joplinapp.org/help/apps/sync/joplin_server.',
      },
      {
        name: 'Vikunja',
        description: 'To-do app with kanban boards, CalDAV sync, and team collaboration.',
        websiteUrl: 'https://vikunja.io',
        sourceCodeUrl: 'https://kolaente.dev/vikunja/vikunja',
        stars: 1000,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d -p 3456:3456 -v /path/data:/app/vikunja/files vikunja/vikunja`. See vikunja.io/docs/installing for database configuration (SQLite by default, Postgres/MySQL supported).',
      },
      {
        name: 'LibreOffice',
        description: 'Full office suite — Writer, Calc, Impress — compatible with MS Office files.',
        websiteUrl: 'https://www.libreoffice.org',
        sourceCodeUrl: 'https://github.com/LibreOffice/core',
        stars: 2300,
        license: 'MPL-2.0',
        selfHosted: false,
      },
      {
        name: 'LanguageTool',
        description: 'Multilingual grammar, style, and spell checker — supports 30+ languages.',
        websiteUrl: 'https://languagetool.org',
        sourceCodeUrl: 'https://github.com/languagetool-org/languagetool',
        stars: 12000,
        license: 'LGPL-2.1',
        selfHosted: true,
        installInstructions: 'LanguageTool doesn\'t publish an official Docker image, but the standalone HTTP server can be self-hosted by running `java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081` from the downloadable server package, or via the widely-used community image `erikvl87/languagetool`. See dev.languagetool.org/http-server.',
      },
    ],
  },
  {
    slug: 'communication',
    category: 'Communication',
    emoji: '💬',
    paidServices: ['Slack', 'Zoom', 'Microsoft Teams'],
    alternatives: [
      {
        name: 'Mattermost',
        description: 'Open-source Slack alternative built for secure team collaboration.',
        websiteUrl: 'https://mattermost.com',
        sourceCodeUrl: 'https://github.com/mattermost/mattermost',
        stars: 31000,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Quick single-container trial: `docker run --name mattermost -d --publish 8065:8065 mattermost/mattermost-team-edition`. For production, use the official Docker Compose setup (with Postgres) at docs.mattermost.com/install/install-docker.html.',
      },
      {
        name: 'Rocket.Chat',
        description: 'Fully customisable team chat platform with high data-protection standards.',
        websiteUrl: 'https://rocket.chat',
        sourceCodeUrl: 'https://github.com/RocketChat/Rocket.Chat',
        stars: 41000,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Officially deployed with Docker Compose (Rocket.Chat + MongoDB replica set). Download the official `docker-compose.yml` from docs.rocket.chat/docs/deploy-with-docker-docker-compose and run `docker compose up -d`.',
      },
      {
        name: 'Jitsi Meet',
        description: 'Secure, fully-featured video conferencing — no account required.',
        websiteUrl: 'https://jitsi.org',
        sourceCodeUrl: 'https://github.com/jitsi/jitsi-meet',
        stars: 23000,
        license: 'Apache-2.0',
        selfHosted: true,
        installInstructions: 'Official install method is docker-jitsi-meet: clone github.com/jitsi/docker-jitsi-meet, copy `env.example` to `.env`, run `./gen-passwords.sh` to generate secrets, then `docker compose up -d`.',
      },
    ],
  },
  {
    slug: 'vpn-security',
    category: 'VPN & Password Management',
    emoji: '🔐',
    paidServices: ['NordVPN', 'ExpressVPN', 'Surfshark', '1Password', 'LastPass', 'Dashlane'],
    alternatives: [
      {
        name: 'WireGuard',
        description: 'Fast, modern VPN protocol — pair with a cheap VPS for your own private VPN.',
        websiteUrl: 'https://www.wireguard.com',
        sourceCodeUrl: 'https://www.wireguard.com/repositories/',
        stars: 0,
        license: 'GPL-2.0',
        selfHosted: true,
        installInstructions: 'Not a typical containerized web app — install the `wireguard-tools` package on a VPS and configure `wg-quick` per the official quickstart at wireguard.com/quickstart, or use the popular community image `linuxserver/wireguard` for a Docker-based setup.',
      },
      {
        name: 'Vaultwarden',
        description: 'Lightweight Bitwarden-compatible password server in Rust — self-hosted in minutes.',
        websiteUrl: 'https://github.com/dani-garcia/vaultwarden',
        sourceCodeUrl: 'https://github.com/dani-garcia/vaultwarden',
        stars: 40000,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name vaultwarden -p 80:80 -v /path/vw-data:/data vaultwarden/server:latest`. Put it behind HTTPS (reverse proxy) before connecting real Bitwarden clients — see github.com/dani-garcia/vaultwarden/wiki.',
      },
      {
        name: 'KeePassXC',
        description: 'Local-first password manager with browser integration. No subscription, ever.',
        websiteUrl: 'https://keepassxc.org',
        sourceCodeUrl: 'https://github.com/keepassxreboot/keepassxc',
        stars: 22000,
        license: 'GPL-3.0',
        selfHosted: false,
      },
    ],
  },
  {
    slug: 'ai-tools',
    category: 'AI & Machine Learning',
    emoji: '🤖',
    paidServices: ['ChatGPT Plus', 'Claude Pro', 'GitHub Copilot'],
    alternatives: [
      {
        name: 'Ollama',
        description: 'Run Llama, Mistral, and other LLMs locally with a single command.',
        websiteUrl: 'https://ollama.com',
        sourceCodeUrl: 'https://github.com/ollama/ollama',
        stars: 105000,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama`. Then pull a model with `docker exec -it ollama ollama run llama3`. See github.com/ollama/ollama for GPU passthrough options.',
      },
      {
        name: 'Open WebUI',
        description: 'ChatGPT-style web interface for Ollama and other local models.',
        websiteUrl: 'https://openwebui.com',
        sourceCodeUrl: 'https://github.com/open-webui/open-webui',
        stars: 55000,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d -p 3000:8080 -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:main`. Point it at an existing Ollama instance via the `OLLAMA_BASE_URL` env var. See docs.openwebui.com/getting-started.',
      },
      {
        name: 'Continue',
        description: 'Open-source AI code assistant for VS Code and JetBrains, works with local models.',
        websiteUrl: 'https://continue.dev',
        sourceCodeUrl: 'https://github.com/continuedev/continue',
        stars: 19000,
        license: 'Apache-2.0',
        selfHosted: false,
      },
    ],
  },
  {
    slug: 'marketing',
    category: 'Email & Marketing',
    emoji: '📧',
    paidServices: ['Mailchimp', 'ConvertKit', 'Substack'],
    alternatives: [
      {
        name: 'Listmonk',
        description: 'Self-hosted newsletter and mailing list manager — fast and free.',
        websiteUrl: 'https://listmonk.app',
        sourceCodeUrl: 'https://github.com/knadh/listmonk',
        stars: 15000,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker image `listmonk/listmonk` requires a Postgres database. Easiest path is the sample `docker-compose.yml` from the repo (bundles Postgres), then run the one-time `--install` step to set up the schema. See listmonk.app/docs/installation.',
      },
      {
        name: 'Ghost',
        description: 'Modern publishing platform for newsletters and blogs — open source core.',
        websiteUrl: 'https://ghost.org',
        sourceCodeUrl: 'https://github.com/TryGhost/Ghost',
        stars: 47000,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name ghost -e url=https://yourdomain.com -p 2368:2368 ghost:5-alpine`. For production, pair with a MySQL container instead of the built-in SQLite. See ghost.org/docs/install/docker.',
      },
    ],
  },
  {
    slug: 'education',
    category: 'Learning',
    emoji: '🎓',
    paidServices: ['Duolingo Plus', 'Babbel', 'Rosetta Stone'],
    alternatives: [
      {
        name: 'LibreLingo',
        description: 'Community-driven language learning platform — open courses, no ads.',
        websiteUrl: 'https://librelingo.app',
        sourceCodeUrl: 'https://github.com/LibreLingo/LibreLingo',
        stars: 1900,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'LibreLingo builds to a static site rather than a server app — there\'s no official Docker image. Clone the repo, run the build per github.com/LibreLingo/LibreLingo\'s CONTRIBUTING docs, and deploy the generated static files to any web host or static file server.',
      },
      {
        name: 'Anki',
        description: 'Spaced-repetition flashcards — used by language learners and med students worldwide.',
        websiteUrl: 'https://apps.ankiweb.net',
        sourceCodeUrl: 'https://github.com/ankitects/anki',
        stars: 19000,
        license: 'AGPL-3.0',
        selfHosted: false,
      },
    ],
  },
  {
    slug: 'development',
    category: 'Developer Tools',
    emoji: '💻',
    paidServices: ['GitHub', 'GitLab Premium', 'Bitbucket'],
    alternatives: [
      {
        name: 'Gitea',
        description: 'Lightweight, painless self-hosted Git service — the easiest GitHub replacement.',
        websiteUrl: 'https://gitea.com',
        sourceCodeUrl: 'https://github.com/go-gitea/gitea',
        stars: 46000,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name gitea -p 3000:3000 -p 222:22 -v /path/data:/data gitea/gitea:latest`. See docs.gitea.com/installation/install-with-docker for a Compose file with Postgres.',
      },
      {
        name: 'Forgejo',
        description: 'Community-led fork of Gitea — fully featured Git forge, run yours in minutes.',
        websiteUrl: 'https://forgejo.org',
        sourceCodeUrl: 'https://codeberg.org/forgejo/forgejo',
        stars: 2000,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name forgejo -p 3000:3000 -p 222:22 -v /path/data:/data codeberg.org/forgejo/forgejo:latest`. See forgejo.org/docs/latest/admin/installation-docker for Compose setup.',
      },
      {
        name: 'GitLab CE',
        description: 'Complete DevOps platform — Git hosting, CI/CD, issue tracking, container registry.',
        websiteUrl: 'https://about.gitlab.com',
        sourceCodeUrl: 'https://gitlab.com/gitlab-org/gitlab-foss',
        stars: 24000,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run --detach --hostname gitlab.example.com --publish 443:443 --publish 80:80 --publish 22:22 --name gitlab --volume /srv/gitlab/config:/etc/gitlab --volume /srv/gitlab/logs:/var/log/gitlab --volume /srv/gitlab/data:/var/opt/gitlab gitlab/gitlab-ce:latest`. Needs at least 4GB RAM. See docs.gitlab.com/install/docker.',
      },
    ],
  },
]

export function findAlternativesForService(serviceName: string): AlternativeCategory | undefined {
  const target = serviceName.trim().toLowerCase()
  return alternativeCategories.find(cat =>
    cat.paidServices.some(s => s.toLowerCase() === target)
  )
}
