export type OpenSourceAlternative = {
  name: string
  description: string
  /** Paid services this tool replaces; must be a subset of its category's `paidServices`. */
  replaces?: string[]
  websiteUrl: string
  sourceCodeUrl: string
  stars: number
  license: string
  /** Caveat shown under the license badge: open-core carve-outs, source-available terms, mirrors. */
  licenseNote?: string
  selfHosted: boolean
  installInstructions?: string
}

export type AlternativeGroupKey = 'home' | 'work' | 'privacy-it'

export type AlternativeCategory = {
  slug: string
  group: AlternativeGroupKey
  category: string
  emoji: string
  /** Honest caveat shown under the category heading (e.g. "replaces the app, not the catalogue"). */
  note?: string
  paidServices: string[]
  alternatives: OpenSourceAlternative[]
}

/** Date the star counts, licenses, and repo status below were last checked against GitHub. */
export const dataVerifiedAt = '2026-09-26'

export const alternativeGroups: { key: AlternativeGroupKey; label: string; blurb: string }[] = [
  { key: 'home', label: 'Home & Entertainment', blurb: 'Streaming, photos, books, fitness, and smart-home subscriptions' },
  { key: 'work', label: 'Work & Business', blurb: 'Productivity, design, project management, CRM, analytics, and AI tools' },
  { key: 'privacy-it', label: 'Privacy, Security & IT', blurb: 'Storage, VPNs, password managers, backup, and monitoring' },
]

const rawCategories: AlternativeCategory[] = [
  {
    slug: 'media-streaming',
    group: 'home',
    category: 'Media Streaming',
    emoji: '🎬',
    note: 'These tools replace the streaming app, not the catalogue: Jellyfin, Invidious, and PeerTube play your own media files or public videos; they don\'t include Netflix-style shows and films.',
    paidServices: ['Netflix', 'Disney+', 'Max', 'Hulu', 'Paramount+', 'Peacock', 'Crunchyroll', 'Amazon Prime Video', 'YouTube Premium'],
    alternatives: [
      {
        name: 'Jellyfin',
        description: 'Free media system that lets you stream your own movie, TV, and music collection from any device.',
        replaces: ['Netflix', 'Disney+', 'Max', 'Hulu', 'Paramount+', 'Peacock', 'Crunchyroll', 'Amazon Prime Video'],
        websiteUrl: 'https://jellyfin.org',
        sourceCodeUrl: 'https://github.com/jellyfin/jellyfin',
        stars: 57500,
        license: 'GPL-2.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name jellyfin -p 8096:8096 -v /path/to/config:/config -v /path/to/media:/media jellyfin/jellyfin:latest`. See jellyfin.org/docs/general/installation for reverse proxy and hardware transcoding setup.',
      },
      {
        name: 'Invidious',
        description: 'Lightweight YouTube front-end with no ads, no tracking, and no Google account required.',
        replaces: ['YouTube Premium'],
        websiteUrl: 'https://invidious.io',
        sourceCodeUrl: 'https://github.com/iv-org/invidious',
        stars: 24800,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Ships an official `docker-compose.yml` (bundles Postgres) in the repo root — clone github.com/iv-org/invidious, copy `docker-compose.yml.example`, and run `docker compose up -d`. Full instructions at github.com/iv-org/invidious/wiki/Installation.',
      },
      {
        name: 'PeerTube',
        description: 'Decentralised, federated video platform — like a community-run YouTube.',
        replaces: ['YouTube Premium'],
        websiteUrl: 'https://joinpeertube.org',
        sourceCodeUrl: 'https://github.com/Chocobozzz/PeerTube',
        stars: 15300,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Officially deployed via Docker Compose: download the sample `docker-compose.yml` and `.env` from the `support/docker/production` directory of the PeerTube repo, fill in your domain/SMTP settings, then run `docker compose up -d`. See docs.joinpeertube.org/install/docker.',
      },
    ],
  },
  {
    slug: 'music-streaming',
    group: 'home',
    category: 'Music Streaming',
    emoji: '🎵',
    note: 'These tools replace the streaming app, not the catalogue: you supply your own music files.',
    paidServices: ['Spotify', 'Apple Music', 'Tidal', 'YouTube Music'],
    alternatives: [
      {
        name: 'Navidrome',
        description: 'Modern, fast self-hosted music server compatible with Subsonic and Airsonic clients.',
        replaces: ['Spotify', 'Apple Music', 'Tidal', 'YouTube Music'],
        websiteUrl: 'https://www.navidrome.org',
        sourceCodeUrl: 'https://github.com/navidrome/navidrome',
        stars: 23800,
        license: 'GPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name navidrome -p 4533:4533 -v /path/data:/data -v /path/music:/music:ro deluan/navidrome:latest`. See navidrome.org/docs/installation/docker for a Compose example.',
      },
      {
        name: 'Funkwhale',
        description: 'Federated music streaming and sharing platform built for communities.',
        replaces: ['Spotify', 'Apple Music', 'Tidal', 'YouTube Music'],
        websiteUrl: 'https://funkwhale.audio',
        sourceCodeUrl: 'https://dev.funkwhale.audio/funkwhale/funkwhale',
        stars: 1600,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Recommended install is Docker Compose (multiple services: api, celery worker, nginx, Postgres, Redis) — follow the step-by-step guide at docs.funkwhale.audio/administrator/installation/docker.html to generate your `.env` and `docker-compose.yml`.',
      },
    ],
  },
  {
    slug: 'cloud-storage',
    group: 'privacy-it',
    category: 'Cloud Storage',
    emoji: '☁️',
    paidServices: ['Dropbox', 'Google One', 'iCloud+', 'OneDrive'],
    alternatives: [
      {
        name: 'Nextcloud',
        description: 'Full Dropbox/Google Workspace replacement — files, calendar, contacts, notes, video calls.',
        replaces: ['Dropbox', 'Google One', 'iCloud+', 'OneDrive'],
        websiteUrl: 'https://nextcloud.com',
        sourceCodeUrl: 'https://github.com/nextcloud/server',
        stars: 36900,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d -p 8080:80 -v /path/nextcloud:/var/www/html nextcloud:latest`. For production use, pair it with a separate database container (MariaDB/Postgres) as shown in the docs at hub.docker.com/_/nextcloud.',
      },
      {
        name: 'Syncthing',
        description: 'Continuous, peer-to-peer file sync between your devices. No cloud middleman.',
        replaces: ['Dropbox', 'OneDrive'],
        websiteUrl: 'https://syncthing.net',
        sourceCodeUrl: 'https://github.com/syncthing/syncthing',
        stars: 88900,
        license: 'MPL-2.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name syncthing -p 8384:8384 -p 22000:22000/tcp -p 22000:22000/udp -p 21027:21027/udp -v /path/config:/var/syncthing syncthing/syncthing`. See docs.syncthing.net/users/docker.html.',
      },
    ],
  },
  {
    slug: 'design-creative',
    group: 'work',
    category: 'Design & Creative',
    emoji: '🎨',
    paidServices: ['Adobe Creative Cloud', 'Canva Pro', 'Figma', 'Sketch', 'Adobe Photoshop', 'Adobe Lightroom', 'Autodesk Maya'],
    alternatives: [
      {
        name: 'GIMP',
        description: 'Mature raster image editor — the open-source counterpart to Photoshop.',
        replaces: ['Adobe Creative Cloud', 'Adobe Photoshop'],
        websiteUrl: 'https://www.gimp.org',
        sourceCodeUrl: 'https://gitlab.gnome.org/GNOME/gimp',
        stars: 1800,
        license: 'GPL-3.0',
        selfHosted: false,
      },
      {
        name: 'Inkscape',
        description: 'Professional vector graphics editor — an open alternative to Illustrator.',
        replaces: ['Adobe Creative Cloud'],
        websiteUrl: 'https://inkscape.org',
        sourceCodeUrl: 'https://gitlab.com/inkscape/inkscape',
        stars: 2200,
        license: 'GPL-2.0',
        selfHosted: false,
      },
      {
        name: 'Kdenlive',
        description: 'Non-linear video editor with multi-track timelines, effects, and proxy editing.',
        replaces: ['Adobe Creative Cloud'],
        websiteUrl: 'https://kdenlive.org',
        sourceCodeUrl: 'https://invent.kde.org/multimedia/kdenlive',
        stars: 3100,
        license: 'GPL-3.0',
        selfHosted: false,
      },
      {
        name: 'Penpot',
        description: 'Open-source design and prototyping platform — the Figma replacement.',
        replaces: ['Figma', 'Canva Pro', 'Sketch'],
        websiteUrl: 'https://penpot.app',
        sourceCodeUrl: 'https://github.com/penpot/penpot',
        stars: 60400,
        license: 'MPL-2.0',
        selfHosted: true,
        installInstructions: 'Deployed via Docker Compose (frontend, backend, exporter, Postgres, Redis, MinIO/S3 services). Follow the official self-hosting guide at penpot.app/docs/self-hosting to fetch the `docker-compose.yaml` and run `docker compose up -d`.',
      },
      {
        name: 'Darktable',
        description: 'RAW photo workflow and non-destructive editor — a Lightroom alternative.',
        replaces: ['Adobe Lightroom', 'Adobe Creative Cloud'],
        websiteUrl: 'https://www.darktable.org',
        sourceCodeUrl: 'https://github.com/darktable-org/darktable',
        stars: 13100,
        license: 'GPL-3.0',
        selfHosted: false,
      },
      {
        name: 'Krita',
        description: 'Professional digital painting and illustration app with brush engines built for artists.',
        replaces: ['Adobe Photoshop'],
        websiteUrl: 'https://krita.org',
        sourceCodeUrl: 'https://github.com/KDE/krita',
        stars: 10400,
        license: 'GPL-3.0',
        licenseNote: 'The GitHub repo is a mirror of KDE\'s own repository.',
        selfHosted: false,
      },
      {
        name: 'Blender',
        description: 'Complete 3D creation suite: modelling, animation, rendering, and video editing.',
        replaces: ['Autodesk Maya'],
        websiteUrl: 'https://www.blender.org',
        sourceCodeUrl: 'https://github.com/blender/blender',
        stars: 20500,
        license: 'GNU GPL',
        licenseNote: 'The GitHub repo is an official mirror.',
        selfHosted: false,
      },
    ],
  },
  {
    slug: 'productivity',
    group: 'work',
    category: 'Productivity & Notes',
    emoji: '📝',
    paidServices: ['Notion', 'Evernote', 'Todoist', 'Microsoft 365', 'Grammarly', 'Roam Research', 'Confluence', 'Obsidian Sync'],
    alternatives: [
      {
        name: 'AppFlowy',
        description: 'Notion-style workspace for wikis, projects, and docs — all open source.',
        replaces: ['Notion', 'Evernote'],
        websiteUrl: 'https://appflowy.io',
        sourceCodeUrl: 'https://github.com/AppFlowy-IO/AppFlowy',
        stars: 76900,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'The AppFlowy app itself is a desktop client; for self-hosted sync, deploy AppFlowy Cloud via its official `docker-compose.yml` (see github.com/AppFlowy-IO/AppFlowy-Cloud) and point the desktop client at your server URL.',
      },
      {
        name: 'Outline',
        description: 'Fast, collaborative team knowledge base and wiki.',
        replaces: ['Notion', 'Confluence'],
        websiteUrl: 'https://www.getoutline.com',
        sourceCodeUrl: 'https://github.com/outline/outline',
        stars: 40700,
        license: 'BSL-1.1',
        licenseNote: 'Source-available, not OSI open source: free to self-host for your own team, but you may not run it as a commercial document service for third parties. Converts to Apache-2.0 on 2030-09-09.',
        selfHosted: true,
        installInstructions: 'Runs via Docker Compose (needs Postgres, Redis, and S3-compatible storage). Copy the repo\'s `docker-compose.yml` and `.env.sample`, fill in the required secrets, then run `docker compose up`. Full guide at docs.getoutline.com/s/hosting.',
      },
      {
        name: 'Joplin',
        description: 'Cross-platform note-taking app with end-to-end encryption and sync.',
        replaces: ['Evernote'],
        websiteUrl: 'https://joplinapp.org',
        sourceCodeUrl: 'https://github.com/laurent22/joplin',
        stars: 56500,
        license: 'AGPL-3.0',
        licenseNote: 'Joplin apps are AGPL-3.0-or-later; Joplin Server (`packages/server`) ships under its own separate license.',
        selfHosted: true,
        installInstructions: 'For synced notes across devices, self-host Joplin Server via the official image: `docker run -d -p 22300:22300 joplin/server:latest` (requires a Postgres database, configured via env vars). See joplinapp.org/help/apps/sync/joplin_server.',
      },
      {
        name: 'Vikunja',
        description: 'To-do app with kanban boards, CalDAV sync, and team collaboration.',
        replaces: ['Todoist'],
        websiteUrl: 'https://vikunja.io',
        sourceCodeUrl: 'https://kolaente.dev/vikunja/vikunja',
        stars: 1000,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d -p 3456:3456 -v /path/data:/app/vikunja/files vikunja/vikunja`. See vikunja.io/docs/installing for database configuration (SQLite by default, Postgres/MySQL supported).',
      },
      {
        name: 'LibreOffice',
        description: 'Full office suite — Writer, Calc, Impress — compatible with MS Office files.',
        replaces: ['Microsoft 365'],
        websiteUrl: 'https://www.libreoffice.org',
        sourceCodeUrl: 'https://github.com/LibreOffice/core',
        stars: 4400,
        license: 'MPL-2.0',
        selfHosted: false,
      },
      {
        name: 'LanguageTool',
        description: 'Multilingual grammar, style, and spell checker — supports 30+ languages.',
        replaces: ['Grammarly'],
        websiteUrl: 'https://languagetool.org',
        sourceCodeUrl: 'https://github.com/languagetool-org/languagetool',
        stars: 15100,
        license: 'LGPL-2.1',
        selfHosted: true,
        installInstructions: 'LanguageTool doesn\'t publish an official Docker image, but the standalone HTTP server can be self-hosted by running `java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081` from the downloadable server package, or via the widely-used community image `erikvl87/languagetool`. See dev.languagetool.org/http-server.',
      },
      {
        name: 'Logseq',
        description: 'Privacy-first outliner and knowledge base that stores plain local files — a Roam Research and Obsidian alternative.',
        replaces: ['Roam Research', 'Obsidian Sync'],
        websiteUrl: 'https://logseq.com',
        sourceCodeUrl: 'https://github.com/logseq/logseq',
        stars: 45100,
        license: 'AGPL-3.0',
        selfHosted: false,
      },
      {
        name: 'SiYuan',
        description: 'Privacy-first personal knowledge manager with block-level references and a Notion-style editor.',
        replaces: ['Notion', 'Roam Research'],
        websiteUrl: 'https://b3log.org/siyuan/en/',
        sourceCodeUrl: 'https://github.com/siyuan-note/siyuan',
        stars: 46500,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
      {
        name: 'Wiki.js',
        description: 'Modern wiki engine for team documentation — a Confluence alternative.',
        replaces: ['Confluence'],
        websiteUrl: 'https://js.wiki',
        sourceCodeUrl: 'https://github.com/requarks/wiki',
        stars: 29000,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'communication',
    group: 'work',
    category: 'Communication',
    emoji: '💬',
    paidServices: ['Slack', 'Zoom', 'Microsoft Teams'],
    alternatives: [
      {
        name: 'Mattermost',
        description: 'Open-source Slack alternative built for secure team collaboration.',
        replaces: ['Slack', 'Microsoft Teams'],
        websiteUrl: 'https://mattermost.com',
        sourceCodeUrl: 'https://github.com/mattermost/mattermost',
        stars: 39200,
        license: 'AGPL-3.0',
        licenseNote: 'Source is AGPL-3.0 (with exceptions); Mattermost-built binaries are MIT. Enterprise features live under a separate commercial license.',
        selfHosted: true,
        installInstructions: 'Quick single-container trial: `docker run --name mattermost -d --publish 8065:8065 mattermost/mattermost-team-edition`. For production, use the official Docker Compose setup (with Postgres) at docs.mattermost.com/install/install-docker.html.',
      },
      {
        name: 'Rocket.Chat',
        description: 'Fully customisable team chat platform with high data-protection standards.',
        replaces: ['Slack', 'Microsoft Teams'],
        websiteUrl: 'https://rocket.chat',
        sourceCodeUrl: 'https://github.com/RocketChat/Rocket.Chat',
        stars: 46200,
        license: 'MIT',
        licenseNote: 'Open core: MIT except the `ee/` directories, which carry a separate enterprise license.',
        selfHosted: true,
        installInstructions: 'Officially deployed with Docker Compose (Rocket.Chat + MongoDB replica set). Download the official `docker-compose.yml` from docs.rocket.chat/docs/deploy-with-docker-docker-compose and run `docker compose up -d`.',
      },
      {
        name: 'Jitsi Meet',
        description: 'Secure, fully-featured video conferencing — no account required.',
        replaces: ['Zoom', 'Microsoft Teams'],
        websiteUrl: 'https://jitsi.org',
        sourceCodeUrl: 'https://github.com/jitsi/jitsi-meet',
        stars: 30000,
        license: 'Apache-2.0',
        selfHosted: true,
        installInstructions: 'Official install method is docker-jitsi-meet: clone github.com/jitsi/docker-jitsi-meet, copy `env.example` to `.env`, run `./gen-passwords.sh` to generate secrets, then `docker compose up -d`.',
      },
      {
        name: 'Zulip',
        description: 'Team chat that organises every conversation into topics — a Slack alternative for busy channels.',
        replaces: ['Slack'],
        websiteUrl: 'https://zulip.com',
        sourceCodeUrl: 'https://github.com/zulip/zulip',
        stars: 26000,
        license: 'Apache-2.0',
        selfHosted: true,
      },
      {
        name: 'Element (Matrix)',
        description: 'Client for the federated, end-to-end encrypted Matrix network — run your own homeserver or use a hosted one.',
        replaces: ['Slack', 'Microsoft Teams'],
        websiteUrl: 'https://element.io',
        sourceCodeUrl: 'https://github.com/element-hq/element-web',
        stars: 13500,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'vpn-security',
    group: 'privacy-it',
    category: 'VPN & Password Management',
    emoji: '🔐',
    paidServices: ['NordVPN', 'ExpressVPN', 'Surfshark', '1Password', 'LastPass', 'Dashlane'],
    alternatives: [
      {
        name: 'WireGuard',
        description: 'Fast, modern VPN protocol — pair with a cheap VPS for your own private VPN.',
        replaces: ['NordVPN', 'ExpressVPN', 'Surfshark'],
        websiteUrl: 'https://www.wireguard.com',
        sourceCodeUrl: 'https://www.wireguard.com/repositories/',
        stars: 0,
        license: 'GPL-2.0',
        selfHosted: true,
        installInstructions: 'Not a typical containerized web app — install the `wireguard-tools` package on a VPS and configure `wg-quick` per the official quickstart at wireguard.com/quickstart, or use the popular community image `linuxserver/wireguard` for a Docker-based setup.',
      },
      {
        name: 'Vaultwarden',
        description: 'Lightweight Bitwarden-compatible password server in Rust — self-hosted in minutes.',
        replaces: ['1Password', 'LastPass', 'Dashlane'],
        websiteUrl: 'https://github.com/dani-garcia/vaultwarden',
        sourceCodeUrl: 'https://github.com/dani-garcia/vaultwarden',
        stars: 68200,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name vaultwarden -p 80:80 -v /path/vw-data:/data vaultwarden/server:latest`. Put it behind HTTPS (reverse proxy) before connecting real Bitwarden clients — see github.com/dani-garcia/vaultwarden/wiki.',
      },
      {
        name: 'KeePassXC',
        description: 'Local-first password manager with browser integration. No subscription, ever.',
        replaces: ['1Password', 'LastPass', 'Dashlane'],
        websiteUrl: 'https://keepassxc.org',
        sourceCodeUrl: 'https://github.com/keepassxreboot/keepassxc',
        stars: 29000,
        license: 'GPL-3.0',
        selfHosted: false,
      },
    ],
  },
  {
    slug: 'ai-tools',
    group: 'work',
    category: 'AI & Machine Learning',
    emoji: '🤖',
    note: 'Local models need a capable computer or GPU, and quality varies by model compared with hosted services like ChatGPT Plus or Claude Pro.',
    paidServices: ['ChatGPT Plus', 'Claude Pro', 'GitHub Copilot', 'Midjourney', 'Otter.ai', 'DeepL Pro'],
    alternatives: [
      {
        name: 'Ollama',
        description: 'Run Llama, Mistral, and other LLMs locally with a single command.',
        replaces: ['ChatGPT Plus', 'Claude Pro'],
        websiteUrl: 'https://ollama.com',
        sourceCodeUrl: 'https://github.com/ollama/ollama',
        stars: 181800,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama`. Then pull a model with `docker exec -it ollama ollama run llama3`. See github.com/ollama/ollama for GPU passthrough options.',
      },
      {
        name: 'Open WebUI',
        description: 'ChatGPT-style web interface for Ollama and other local models.',
        replaces: ['ChatGPT Plus', 'Claude Pro'],
        websiteUrl: 'https://openwebui.com',
        sourceCodeUrl: 'https://github.com/open-webui/open-webui',
        stars: 153200,
        license: 'Open WebUI License',
        licenseNote: 'BSD-3-Clause-based license with a branding-preservation clause — source is public and free to self-host, but it is not an OSI-approved open source license.',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d -p 3000:8080 -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:main`. Point it at an existing Ollama instance via the `OLLAMA_BASE_URL` env var. See docs.openwebui.com/getting-started.',
      },
      {
        name: 'Continue',
        description: 'Open-source AI code assistant for VS Code and JetBrains, works with local models.',
        replaces: ['GitHub Copilot'],
        websiteUrl: 'https://continue.dev',
        sourceCodeUrl: 'https://github.com/continuedev/continue',
        stars: 36000,
        license: 'Apache-2.0',
        selfHosted: false,
      },
      {
        name: 'ComfyUI',
        description: 'Node-based interface for running Stable Diffusion and other image-generation models locally — a Midjourney alternative if you have a capable GPU.',
        replaces: ['Midjourney'],
        websiteUrl: 'https://www.comfy.org',
        sourceCodeUrl: 'https://github.com/Comfy-Org/ComfyUI',
        stars: 135000,
        license: 'GPL-3.0',
        selfHosted: true,
      },
      {
        name: 'Whisper',
        description: 'Speech-to-text model that runs locally — the engine behind many free transcription apps, and the basis for an Otter.ai-style workflow.',
        replaces: ['Otter.ai'],
        websiteUrl: 'https://github.com/openai/whisper',
        sourceCodeUrl: 'https://github.com/openai/whisper',
        stars: 109600,
        license: 'MIT',
        selfHosted: true,
      },
      {
        name: 'LibreTranslate',
        description: 'Self-hosted machine translation API — a DeepL alternative, with quality that varies by language pair.',
        replaces: ['DeepL Pro'],
        websiteUrl: 'https://libretranslate.com',
        sourceCodeUrl: 'https://github.com/LibreTranslate/LibreTranslate',
        stars: 16800,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'marketing',
    group: 'work',
    category: 'Email & Marketing',
    emoji: '📧',
    paidServices: ['Mailchimp', 'ConvertKit', 'Substack', 'Bitly'],
    alternatives: [
      {
        name: 'Listmonk',
        description: 'Self-hosted newsletter and mailing list manager — fast and free.',
        replaces: ['Mailchimp', 'ConvertKit', 'Substack'],
        websiteUrl: 'https://listmonk.app',
        sourceCodeUrl: 'https://github.com/knadh/listmonk',
        stars: 23600,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker image `listmonk/listmonk` requires a Postgres database. Easiest path is the sample `docker-compose.yml` from the repo (bundles Postgres), then run the one-time `--install` step to set up the schema. See listmonk.app/docs/installation.',
      },
      {
        name: 'Ghost',
        description: 'Modern publishing platform for newsletters and blogs — open source core.',
        replaces: ['Substack'],
        websiteUrl: 'https://ghost.org',
        sourceCodeUrl: 'https://github.com/TryGhost/Ghost',
        stars: 55400,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name ghost -e url=https://yourdomain.com -p 2368:2368 ghost:5-alpine`. For production, pair with a MySQL container instead of the built-in SQLite. See ghost.org/docs/install/docker.',
      },
      {
        name: 'Shlink',
        description: 'Self-hosted URL shortener with click analytics and a REST API — a Bitly alternative.',
        replaces: ['Bitly'],
        websiteUrl: 'https://github.com/shlinkio/shlink',
        sourceCodeUrl: 'https://github.com/shlinkio/shlink',
        stars: 5300,
        license: 'MIT',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'education',
    group: 'home',
    category: 'Learning',
    emoji: '🎓',
    note: 'Anki covers vocabulary and spaced-repetition study; it doesn\'t include guided lessons like Duolingo or Babbel.',
    paidServices: ['Duolingo Plus', 'Babbel', 'Rosetta Stone'],
    alternatives: [
      {
        name: 'Anki',
        description: 'Spaced-repetition flashcards — used by language learners and med students worldwide.',
        replaces: ['Duolingo Plus', 'Babbel', 'Rosetta Stone'],
        websiteUrl: 'https://apps.ankiweb.net',
        sourceCodeUrl: 'https://github.com/ankitects/anki',
        stars: 31600,
        license: 'AGPL-3.0',
        selfHosted: false,
      },
    ],
  },
  {
    slug: 'development',
    group: 'work',
    category: 'Developer Tools',
    emoji: '💻',
    paidServices: ['GitHub', 'GitLab Premium', 'Bitbucket'],
    alternatives: [
      {
        name: 'Gitea',
        description: 'Lightweight, painless self-hosted Git service — the easiest GitHub replacement.',
        replaces: ['GitHub', 'Bitbucket'],
        websiteUrl: 'https://gitea.com',
        sourceCodeUrl: 'https://github.com/go-gitea/gitea',
        stars: 58200,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name gitea -p 3000:3000 -p 222:22 -v /path/data:/data gitea/gitea:latest`. See docs.gitea.com/installation/install-with-docker for a Compose file with Postgres.',
      },
      {
        name: 'Forgejo',
        description: 'Community-led fork of Gitea — fully featured Git forge, run yours in minutes.',
        replaces: ['GitHub', 'Bitbucket'],
        websiteUrl: 'https://forgejo.org',
        sourceCodeUrl: 'https://codeberg.org/forgejo/forgejo',
        stars: 2000,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run -d --name forgejo -p 3000:3000 -p 222:22 -v /path/data:/data codeberg.org/forgejo/forgejo:latest`. See forgejo.org/docs/latest/admin/installation-docker for Compose setup.',
      },
      {
        name: 'GitLab CE',
        description: 'Complete DevOps platform — Git hosting, CI/CD, issue tracking, container registry.',
        replaces: ['GitLab Premium', 'GitHub', 'Bitbucket'],
        websiteUrl: 'https://about.gitlab.com',
        sourceCodeUrl: 'https://gitlab.com/gitlab-org/gitlab-foss',
        stars: 24000,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official Docker image: `docker run --detach --hostname gitlab.example.com --publish 443:443 --publish 80:80 --publish 22:22 --name gitlab --volume /srv/gitlab/config:/etc/gitlab --volume /srv/gitlab/logs:/var/log/gitlab --volume /srv/gitlab/data:/var/opt/gitlab gitlab/gitlab-ce:latest`. Needs at least 4GB RAM. See docs.gitlab.com/install/docker.',
      },
    ],
  },
  {
    slug: 'photo-backup',
    group: 'home',
    category: 'Photo & Video Backup',
    emoji: '📸',
    paidServices: ['Google Photos', 'Amazon Photos', 'Flickr Pro'],
    alternatives: [
      {
        name: 'Immich',
        description: 'Self-hosted photo and video backup with mobile apps, face recognition, and shared albums — the closest Google Photos replacement.',
        replaces: ['Google Photos', 'Amazon Photos', 'Flickr Pro'],
        websiteUrl: 'https://immich.app',
        sourceCodeUrl: 'https://github.com/immich-app/immich',
        stars: 115100,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker Compose install guide: docs.immich.app/install/docker-compose.',
      },
      {
        name: 'PhotoPrism',
        description: 'AI-assisted photo library for browsing, searching, and organising large collections on your own server.',
        replaces: ['Google Photos', 'Amazon Photos', 'Flickr Pro'],
        websiteUrl: 'https://www.photoprism.app',
        sourceCodeUrl: 'https://github.com/photoprism/photoprism',
        stars: 40200,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker Compose install guide: docs.photoprism.app/getting-started/docker-compose.',
      },
      {
        name: 'Ente',
        description: 'End-to-end encrypted photo storage with open-source apps and server — self-host it or use their paid hosting.',
        replaces: ['Google Photos', 'Amazon Photos'],
        websiteUrl: 'https://ente.io',
        sourceCodeUrl: 'https://github.com/ente/ente',
        stars: 29100,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'books-audiobooks',
    group: 'home',
    category: 'Audiobooks, Ebooks & Comics',
    emoji: '📚',
    note: 'These tools organise and read books you already own; they don\'t include a catalogue like Audible or Kindle Unlimited.',
    paidServices: ['Audible', 'Kindle Unlimited', 'Scribd', 'Marvel Unlimited'],
    alternatives: [
      {
        name: 'Audiobookshelf',
        description: 'Self-hosted audiobook and podcast server with progress sync and mobile apps — for audiobooks you already own.',
        replaces: ['Audible'],
        websiteUrl: 'https://www.audiobookshelf.org',
        sourceCodeUrl: 'https://github.com/advplyr/audiobookshelf',
        stars: 14400,
        license: 'GPL-3.0',
        selfHosted: true,
        installInstructions: 'Official install docs: audiobookshelf.org/docs.',
      },
      {
        name: 'Calibre-Web',
        description: 'Web interface for browsing, reading, and downloading ebooks from a Calibre library.',
        replaces: ['Kindle Unlimited', 'Scribd'],
        websiteUrl: 'https://github.com/janeczku/calibre-web',
        sourceCodeUrl: 'https://github.com/janeczku/calibre-web',
        stars: 18200,
        license: 'GPL-3.0',
        selfHosted: true,
      },
      {
        name: 'Kavita',
        description: 'Fast, cross-platform reading server for manga, comics, and ebooks with a built-in reader.',
        replaces: ['Marvel Unlimited'],
        websiteUrl: 'https://www.kavitareader.com',
        sourceCodeUrl: 'https://github.com/Kareadita/Kavita',
        stars: 11700,
        license: 'GPL-3.0',
        selfHosted: true,
      },
      {
        name: 'Komga',
        description: 'Media server for comics, manga, and magazines with OPDS support and a web reader.',
        replaces: ['Marvel Unlimited'],
        websiteUrl: 'https://komga.org',
        sourceCodeUrl: 'https://github.com/gotson/komga',
        stars: 6700,
        license: 'MIT',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'read-later-rss',
    group: 'home',
    category: 'Read-Later & RSS',
    emoji: '📰',
    paidServices: ['Instapaper Premium', 'Feedly Pro', 'Inoreader Pro', 'Readwise Reader'],
    alternatives: [
      {
        name: 'Wallabag',
        description: 'Save web articles to read later, stripped of clutter, with browser extensions and mobile apps.',
        replaces: ['Instapaper Premium', 'Readwise Reader'],
        websiteUrl: 'https://wallabag.org',
        sourceCodeUrl: 'https://github.com/wallabag/wallabag',
        stars: 13000,
        license: 'MIT',
        selfHosted: true,
      },
      {
        name: 'Miniflux',
        description: 'Minimalist, fast RSS feed reader — a single Go binary backed by Postgres.',
        replaces: ['Feedly Pro', 'Inoreader Pro'],
        websiteUrl: 'https://miniflux.app',
        sourceCodeUrl: 'https://github.com/miniflux/v2',
        stars: 9700,
        license: 'Apache-2.0',
        selfHosted: true,
      },
      {
        name: 'FreshRSS',
        description: 'Self-hosted RSS aggregator with multi-user support, extensions, and mobile-client API compatibility.',
        replaces: ['Feedly Pro', 'Inoreader Pro'],
        websiteUrl: 'https://freshrss.org',
        sourceCodeUrl: 'https://github.com/FreshRSS/FreshRSS',
        stars: 16100,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'health-fitness-recipes',
    group: 'home',
    category: 'Fitness, Nutrition & Recipes',
    emoji: '🥗',
    paidServices: ['MyFitnessPal Premium', 'Strava', 'Fitbod', 'Yummly Pro', 'Mealime Pro'],
    alternatives: [
      {
        name: 'wger',
        description: 'Self-hosted workout planner, exercise database, and nutrition tracker.',
        replaces: ['MyFitnessPal Premium', 'Fitbod'],
        websiteUrl: 'https://wger.de',
        sourceCodeUrl: 'https://github.com/wger-project/wger',
        stars: 7000,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
      {
        name: 'Endurain',
        description: 'Self-hosted fitness tracking app for activities from Garmin and Strava-style GPS files. Younger project with a smaller community.',
        replaces: ['Strava'],
        websiteUrl: 'https://github.com/endurain-project/endurain',
        sourceCodeUrl: 'https://github.com/endurain-project/endurain',
        stars: 2200,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
      {
        name: 'Mealie',
        description: 'Recipe manager and meal planner that imports recipes from URLs and builds shopping lists.',
        replaces: ['Yummly Pro', 'Mealime Pro'],
        websiteUrl: 'https://mealie.io',
        sourceCodeUrl: 'https://github.com/mealie-recipes/mealie',
        stars: 13300,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'smart-home',
    group: 'home',
    category: 'Smart Home & Camera Subscriptions',
    emoji: '🏠',
    note: 'Frigate works with cameras that expose a local RTSP or ONVIF stream. Many vendor cameras (including most Ring and Nest models) don\'t, so switching may mean new camera hardware.',
    paidServices: ['Ring Protect', 'Google Nest Aware', 'Arlo Secure', 'Wyze Cam Plus'],
    alternatives: [
      {
        name: 'Home Assistant',
        description: 'Local-first home automation hub that controls thousands of devices without routing through a vendor cloud.',
        replaces: [],
        websiteUrl: 'https://www.home-assistant.io',
        sourceCodeUrl: 'https://github.com/home-assistant/core',
        stars: 91200,
        license: 'Apache-2.0',
        selfHosted: true,
        installInstructions: 'Official installation guide: home-assistant.io/installation.',
      },
      {
        name: 'Frigate',
        description: 'Local network video recorder with AI object detection for cameras that offer a local RTSP or ONVIF stream — no per-camera cloud plan.',
        replaces: ['Ring Protect', 'Google Nest Aware', 'Arlo Secure', 'Wyze Cam Plus'],
        websiteUrl: 'https://frigate.video',
        sourceCodeUrl: 'https://github.com/blakeblackshear/frigate',
        stars: 36100,
        license: 'MIT',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'video-audio',
    group: 'work',
    category: 'Video, Audio & Screen Recording',
    emoji: '🎥',
    paidServices: ['Loom', 'Camtasia', 'Streamlabs', 'Adobe Premiere Pro', 'Adobe Audition'],
    alternatives: [
      {
        name: 'Cap',
        description: 'Open-source screen recorder with instant shareable links — a Loom alternative.',
        replaces: ['Loom'],
        websiteUrl: 'https://cap.so',
        sourceCodeUrl: 'https://github.com/CapSoftware/Cap',
        stars: 22800,
        license: 'AGPL-3.0',
        licenseNote: 'AGPL-3.0, except the `cap-camera*` and `scap-*` crates, which are MIT.',
        selfHosted: true,
      },
      {
        name: 'OBS Studio',
        description: 'Free software for screen recording and live streaming with scenes, sources, and plugins.',
        replaces: ['Loom', 'Streamlabs', 'Camtasia'],
        websiteUrl: 'https://obsproject.com',
        sourceCodeUrl: 'https://github.com/obsproject/obs-studio',
        stars: 76600,
        license: 'GPL-2.0',
        selfHosted: false,
      },
      {
        name: 'Shotcut',
        description: 'Cross-platform video editor with a wide format range — a Premiere Pro alternative for everyday editing.',
        replaces: ['Adobe Premiere Pro', 'Camtasia'],
        websiteUrl: 'https://shotcut.org',
        sourceCodeUrl: 'https://github.com/mltframework/shotcut',
        stars: 15300,
        license: 'GPL-3.0',
        selfHosted: false,
      },
      {
        name: 'Audacity',
        description: 'Multi-track audio editor and recorder for podcasts, voiceovers, and music.',
        replaces: ['Adobe Audition'],
        websiteUrl: 'https://www.audacityteam.org',
        sourceCodeUrl: 'https://github.com/audacity/audacity',
        stars: 18600,
        license: 'GPL-3.0',
        selfHosted: false,
      },
    ],
  },
  {
    slug: 'project-management',
    group: 'work',
    category: 'Project & Task Management',
    emoji: '📋',
    paidServices: ['Trello', 'Asana', 'Jira', 'Monday.com', 'ClickUp'],
    alternatives: [
      {
        name: 'Plane',
        description: 'Open-source project management with issues, cycles, modules, and views — a Jira and Linear alternative.',
        replaces: ['Jira', 'Asana', 'Monday.com', 'ClickUp', 'Trello'],
        websiteUrl: 'https://plane.so',
        sourceCodeUrl: 'https://github.com/makeplane/plane',
        stars: 59900,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official self-hosting docs: docs.plane.so/self-hosting/overview.',
      },
      {
        name: 'Kanboard',
        description: 'Minimal, no-frills kanban board that runs on almost any PHP host.',
        replaces: ['Trello'],
        websiteUrl: 'https://kanboard.org',
        sourceCodeUrl: 'https://github.com/kanboard/kanboard',
        stars: 9900,
        license: 'MIT',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'whiteboards-diagrams',
    group: 'work',
    category: 'Whiteboards & Diagrams',
    emoji: '✏️',
    paidServices: ['Miro', 'Lucidchart', 'FigJam'],
    alternatives: [
      {
        name: 'Excalidraw',
        description: 'Hand-drawn-style virtual whiteboard with real-time collaboration and end-to-end encrypted sharing.',
        replaces: ['Miro', 'FigJam'],
        websiteUrl: 'https://excalidraw.com',
        sourceCodeUrl: 'https://github.com/excalidraw/excalidraw',
        stars: 133000,
        license: 'MIT',
        selfHosted: true,
      },
      {
        name: 'draw.io (diagrams.net)',
        description: 'Full-featured diagramming tool for flowcharts, UML, network diagrams, and more — runs in the browser or offline.',
        replaces: ['Lucidchart'],
        websiteUrl: 'https://www.drawio.com',
        sourceCodeUrl: 'https://github.com/jgraph/drawio',
        stars: 8400,
        license: 'Apache-2.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'scheduling-forms-signing',
    group: 'work',
    category: 'Scheduling, Forms & E-Signatures',
    emoji: '🗓️',
    paidServices: ['Calendly', 'Acuity Scheduling', 'Typeform', 'SurveyMonkey', 'DocuSign'],
    alternatives: [
      {
        name: 'Cal.diy (Cal.com community edition)',
        description: 'MIT-licensed community edition of Cal.com for self-hosted booking pages — a Calendly alternative.',
        replaces: ['Calendly', 'Acuity Scheduling'],
        websiteUrl: 'https://github.com/calcom/cal.diy',
        sourceCodeUrl: 'https://github.com/calcom/cal.diy',
        stars: 48700,
        license: 'MIT',
        licenseNote: 'A fork of Cal.com with all enterprise code removed. The maintainers recommend it for personal, non-production use; commercial deployments are pointed to Cal.com.',
        selfHosted: true,
      },
      {
        name: 'Formbricks',
        description: 'Survey and form platform for in-product feedback and forms — a Typeform and Qualtrics alternative.',
        replaces: ['Typeform', 'SurveyMonkey'],
        websiteUrl: 'https://formbricks.com',
        sourceCodeUrl: 'https://github.com/formbricks/formbricks',
        stars: 13000,
        license: 'AGPL-3.0',
        licenseNote: 'Open core: AGPL-3.0 except the `ee` directories, which carry a separate enterprise license.',
        selfHosted: true,
      },
      {
        name: 'Documenso',
        description: 'Open-source document signing — a DocuSign alternative you can self-host.',
        replaces: ['DocuSign'],
        websiteUrl: 'https://documenso.com',
        sourceCodeUrl: 'https://github.com/documenso/documenso',
        stars: 15200,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'crm-support',
    group: 'work',
    category: 'CRM & Customer Support',
    emoji: '🤝',
    paidServices: ['HubSpot', 'Salesforce', 'Pipedrive', 'Intercom', 'Zendesk'],
    alternatives: [
      {
        name: 'Twenty',
        description: 'Modern open-source CRM with customisable objects and views — a Salesforce and HubSpot alternative.',
        replaces: ['Salesforce', 'HubSpot', 'Pipedrive'],
        websiteUrl: 'https://twenty.com',
        sourceCodeUrl: 'https://github.com/twentyhq/twenty',
        stars: 57500,
        license: 'AGPL-3.0',
        licenseNote: 'Open core: mostly AGPL-3.0, but files marked `@license Enterprise` are under a commercial license.',
        selfHosted: true,
      },
      {
        name: 'Chatwoot',
        description: 'Open-source customer support desk with live chat, email, and social inboxes — an Intercom and Zendesk alternative.',
        replaces: ['Intercom', 'Zendesk'],
        websiteUrl: 'https://www.chatwoot.com',
        sourceCodeUrl: 'https://github.com/chatwoot/chatwoot',
        stars: 37200,
        license: 'MIT',
        licenseNote: 'Open core: MIT except the `enterprise/` directory, which carries a separate license.',
        selfHosted: true,
      },
      {
        name: 'SuiteCRM',
        description: 'Long-running open-source CRM for sales, marketing, and support workflows.',
        replaces: ['Salesforce', 'HubSpot'],
        websiteUrl: 'https://suitecrm.com',
        sourceCodeUrl: 'https://github.com/SuiteCRM/SuiteCRM',
        stars: 5800,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'personal-finance',
    group: 'work',
    category: 'Budgeting & Personal Finance',
    emoji: '💰',
    paidServices: ['YNAB', 'Monarch Money', 'Quicken', 'Copilot Money'],
    alternatives: [
      {
        name: 'Actual Budget',
        description: 'Local-first envelope-budgeting app with optional self-hosted sync — a YNAB alternative.',
        replaces: ['YNAB', 'Monarch Money', 'Copilot Money'],
        websiteUrl: 'https://actualbudget.org',
        sourceCodeUrl: 'https://github.com/actualbudget/actual',
        stars: 29200,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official install docs: actualbudget.org/docs/install.',
      },
      {
        name: 'Firefly III',
        description: 'Self-hosted personal finance manager with budgets, rules, recurring transactions, and reports.',
        replaces: ['Quicken', 'YNAB', 'Monarch Money'],
        websiteUrl: 'https://www.firefly-iii.org',
        sourceCodeUrl: 'https://github.com/firefly-iii/firefly-iii',
        stars: 24700,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official Docker install guide: docs.firefly-iii.org/how-to/firefly-iii/installation/docker.',
      },
    ],
  },
  {
    slug: 'automation',
    group: 'work',
    category: 'Workflow Automation',
    emoji: '⚡',
    paidServices: ['Zapier', 'IFTTT', 'Make'],
    alternatives: [
      {
        name: 'Activepieces',
        description: 'No-code workflow automation with hundreds of integrations — a Zapier alternative.',
        replaces: ['Zapier', 'Make', 'IFTTT'],
        websiteUrl: 'https://www.activepieces.com',
        sourceCodeUrl: 'https://github.com/activepieces/activepieces',
        stars: 24700,
        license: 'MIT',
        licenseNote: 'Open core: MIT except the `ee` packages, which carry a separate enterprise license.',
        selfHosted: true,
      },
      {
        name: 'Node-RED',
        description: 'Flow-based visual programming tool for wiring together APIs, devices, and online services.',
        replaces: ['Zapier', 'IFTTT'],
        websiteUrl: 'https://nodered.org',
        sourceCodeUrl: 'https://github.com/node-red/node-red',
        stars: 23700,
        license: 'Apache-2.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'websites-stores',
    group: 'work',
    category: 'Websites & Online Stores',
    emoji: '🛒',
    paidServices: ['Shopify', 'Squarespace', 'Wix', 'Webflow'],
    alternatives: [
      {
        name: 'WordPress',
        description: 'The most widely used website and blog platform, with a huge plugin and theme ecosystem.',
        replaces: ['Squarespace', 'Wix', 'Webflow'],
        websiteUrl: 'https://wordpress.org',
        sourceCodeUrl: 'https://github.com/WordPress/WordPress',
        stars: 21400,
        license: 'GPL-2.0-or-later',
        licenseNote: 'The GitHub repo is a read-only mirror of the official Subversion repository.',
        selfHosted: true,
      },
      {
        name: 'Medusa',
        description: 'Headless commerce platform for building custom online stores — a Shopify alternative for developers.',
        replaces: ['Shopify'],
        websiteUrl: 'https://medusajs.com',
        sourceCodeUrl: 'https://github.com/medusajs/medusa',
        stars: 36500,
        license: 'MIT',
        licenseNote: 'Open core: MIT except the Enterprise Edition materials listed in `ENTERPRISE-LICENSE.md`.',
        selfHosted: true,
      },
      {
        name: 'Saleor',
        description: 'GraphQL-first headless commerce platform for multi-channel storefronts.',
        replaces: ['Shopify'],
        websiteUrl: 'https://saleor.io',
        sourceCodeUrl: 'https://github.com/saleor/saleor',
        stars: 23400,
        license: 'BSD-3-Clause',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'web-analytics',
    group: 'work',
    category: 'Web Analytics',
    emoji: '📈',
    paidServices: ['Fathom Analytics', 'Simple Analytics', 'Google Analytics 360'],
    alternatives: [
      {
        name: 'Umami',
        description: 'Simple, privacy-focused web analytics with a cookieless tracker.',
        replaces: ['Fathom Analytics', 'Simple Analytics'],
        websiteUrl: 'https://umami.is',
        sourceCodeUrl: 'https://github.com/umami-software/umami',
        stars: 39000,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official install docs: umami.is/docs/install.',
      },
      {
        name: 'Plausible Community Edition',
        description: 'Lightweight, privacy-friendly analytics dashboard — a Google Analytics alternative.',
        replaces: ['Fathom Analytics', 'Simple Analytics'],
        websiteUrl: 'https://plausible.io',
        sourceCodeUrl: 'https://github.com/plausible/analytics',
        stars: 29200,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official self-hosting docs: plausible.io/docs/self-hosting.',
      },
      {
        name: 'Matomo',
        description: 'Full-featured web analytics platform that gives you 100% data ownership.',
        replaces: ['Google Analytics 360'],
        websiteUrl: 'https://matomo.org',
        sourceCodeUrl: 'https://github.com/matomo-org/matomo',
        stars: 21900,
        license: 'GPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'communities-courses',
    group: 'work',
    category: 'Communities & Online Courses',
    emoji: '🎒',
    paidServices: ['Circle', 'Mighty Networks', 'Teachable', 'Kajabi', 'Thinkific'],
    alternatives: [
      {
        name: 'Discourse',
        description: 'Modern forum and community platform used by thousands of communities.',
        replaces: ['Circle', 'Mighty Networks'],
        websiteUrl: 'https://www.discourse.org',
        sourceCodeUrl: 'https://github.com/discourse/discourse',
        stars: 47900,
        license: 'GPL-2.0',
        selfHosted: true,
      },
      {
        name: 'Moodle',
        description: 'The most widely used open-source learning management system for courses and training.',
        replaces: ['Teachable', 'Kajabi', 'Thinkific'],
        websiteUrl: 'https://moodle.org',
        sourceCodeUrl: 'https://github.com/moodle/moodle',
        stars: 7400,
        license: 'GPL-3.0',
        selfHosted: true,
      },
      {
        name: 'Frappe LMS',
        description: 'Simple, modern learning platform for creating and selling courses. Smaller community than Moodle.',
        replaces: ['Teachable', 'Kajabi', 'Thinkific'],
        websiteUrl: 'https://frappe.io/lms',
        sourceCodeUrl: 'https://github.com/frappe/lms',
        stars: 3300,
        license: 'AGPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'ad-blocking-dns',
    group: 'privacy-it',
    category: 'Ad Blocking & DNS Filtering',
    emoji: '🚫',
    paidServices: ['NextDNS', 'AdGuard Premium'],
    alternatives: [
      {
        name: 'Pi-hole',
        description: 'Network-wide ad and tracker blocking via a local DNS sinkhole.',
        replaces: ['NextDNS'],
        websiteUrl: 'https://pi-hole.net',
        sourceCodeUrl: 'https://github.com/pi-hole/pi-hole',
        stars: 61100,
        license: 'EUPL-1.2',
        selfHosted: true,
        installInstructions: 'Official install docs: docs.pi-hole.net/main/basic-install.',
      },
      {
        name: 'AdGuard Home',
        description: 'Network-wide ad blocker and DNS server with a polished web UI and DNS-over-HTTPS support.',
        replaces: ['NextDNS', 'AdGuard Premium'],
        websiteUrl: 'https://adguard.com/en/adguard-home/overview.html',
        sourceCodeUrl: 'https://github.com/AdguardTeam/AdGuardHome',
        stars: 37100,
        license: 'GPL-3.0',
        selfHosted: true,
      },
    ],
  },
  {
    slug: 'backup',
    group: 'privacy-it',
    category: 'Backup',
    emoji: '💾',
    note: 'These are backup programs, not storage. You still need somewhere to put the backups — a spare drive, a NAS, or low-cost object storage.',
    paidServices: ['Backblaze', 'Carbonite', 'iDrive', 'Acronis'],
    alternatives: [
      {
        name: 'restic',
        description: 'Fast, encrypted, deduplicated backups to local disks, SFTP, or S3-compatible storage.',
        replaces: ['Backblaze', 'Carbonite', 'iDrive', 'Acronis'],
        websiteUrl: 'https://restic.net',
        sourceCodeUrl: 'https://github.com/restic/restic',
        stars: 36300,
        license: 'BSD-2-Clause',
        selfHosted: false,
      },
      {
        name: 'Kopia',
        description: 'Cross-platform backup tool with a GUI, encryption, and deduplication.',
        replaces: ['Backblaze', 'Carbonite', 'iDrive', 'Acronis'],
        websiteUrl: 'https://kopia.io',
        sourceCodeUrl: 'https://github.com/kopia/kopia',
        stars: 14200,
        license: 'Apache-2.0',
        selfHosted: false,
      },
      {
        name: 'Duplicati',
        description: 'Encrypted, incremental backups to cloud storage services and remote file servers.',
        replaces: ['Backblaze', 'Carbonite', 'iDrive', 'Acronis'],
        websiteUrl: 'https://duplicati.com',
        sourceCodeUrl: 'https://github.com/duplicati/duplicati',
        stars: 15000,
        license: 'MIT',
        licenseNote: 'Open core: MIT except the `proprietary/` directory, which carries a separate license.',
        selfHosted: false,
      },
    ],
  },
  {
    slug: 'remote-access',
    group: 'privacy-it',
    category: 'Remote Desktop',
    emoji: '🖥️',
    paidServices: ['TeamViewer', 'AnyDesk', 'LogMeIn', 'Splashtop'],
    alternatives: [
      {
        name: 'RustDesk',
        description: 'Open-source remote desktop with a self-hostable relay server — a TeamViewer and AnyDesk alternative.',
        replaces: ['TeamViewer', 'AnyDesk', 'LogMeIn', 'Splashtop'],
        websiteUrl: 'https://rustdesk.com',
        sourceCodeUrl: 'https://github.com/rustdesk/rustdesk',
        stars: 124600,
        license: 'AGPL-3.0',
        selfHosted: true,
        installInstructions: 'Official self-hosting docs: rustdesk.com/docs/en/self-host.',
      },
    ],
  },
  {
    slug: 'uptime-monitoring',
    group: 'privacy-it',
    category: 'Uptime Monitoring',
    emoji: '📡',
    paidServices: ['UptimeRobot', 'Pingdom', 'StatusCake', 'Better Stack'],
    alternatives: [
      {
        name: 'Uptime Kuma',
        description: 'Self-hosted monitoring tool with a clean dashboard, status pages, and dozens of notification channels.',
        replaces: ['UptimeRobot', 'Pingdom', 'StatusCake', 'Better Stack'],
        websiteUrl: 'https://uptime.kuma.pet',
        sourceCodeUrl: 'https://github.com/louislam/uptime-kuma',
        stars: 91800,
        license: 'MIT',
        selfHosted: true,
        installInstructions: 'Official install guide: github.com/louislam/uptime-kuma/wiki/🔧-How-to-Install.',
      },
    ],
  },
]

const groupOrder = alternativeGroups.map(g => g.key)

/** Categories ordered by group (stable within each group). */
export const alternativeCategories: AlternativeCategory[] = [...rawCategories].sort(
  (a, b) => groupOrder.indexOf(a.group) - groupOrder.indexOf(b.group)
)

export const totalAlternatives = alternativeCategories.reduce((n, c) => n + c.alternatives.length, 0)

export function findAlternativesForService(serviceName: string): AlternativeCategory | undefined {
  const target = serviceName.trim().toLowerCase()
  const cat = alternativeCategories.find(c =>
    c.paidServices.some(s => s.toLowerCase() === target)
  )
  if (!cat) return undefined
  // Narrow to tools that actually replace this service (e.g. Netflix -> Jellyfin, not Invidious).
  const precise = cat.alternatives.filter(a =>
    a.replaces?.some(s => s.toLowerCase() === target)
  )
  return precise.length > 0 ? { ...cat, alternatives: precise } : cat
}
